import type { AgeProfile } from "./types";

export const AGE_PROFILES: AgeProfile[] = [
  {
    id: "age_23_27",
    label: "23–27｜年轻都市",
    ageMin: 23,
    ageMax: 27,
    lifeStageTone: "early independent urban adulthood",
    visualMaturity: "young adult, polished but not overly mature",
    stylingAttitude: "clean, current, restrained, naturally styled",
    socialEnergy: "light, self-directed, responsive",
    bodyLanguageGuidance: [
      "Use natural direct movement with a slightly lighter rhythm.",
      "Keep gestures measured and unrehearsed.",
      "Do not add girlish posing or campus-student behavior.",
    ],
    performanceGuardrails: [
      "no girlish posing",
      "no campus stereotype",
      "no exaggerated cuteness",
      "no trend-chasing influencer behavior",
      "no youth-coded performance for its own sake",
    ],
    status: "ACTIVE",
  },
  {
    id: "age_28_32",
    label: "28–32｜都市轻熟",
    ageMin: 28,
    ageMax: 32,
    lifeStageTone: "settled young urban adulthood",
    visualMaturity: "polished, composed, still light in presence",
    stylingAttitude: "refined everyday dressing",
    socialEnergy: "balanced, natural, socially comfortable",
    bodyLanguageGuidance: [
      "Use an easy, balanced rhythm with composed posture.",
      "Keep movement natural and socially unforced.",
    ],
    performanceGuardrails: [
      "no girlish presentation",
      "no forced mature-woman stereotype",
      "no influencer performance",
      "no default corporate-elite persona",
    ],
    status: "ACTIVE",
  },
  {
    id: "age_33_37",
    label: "33–37｜成熟都市",
    ageMin: 33,
    ageMax: 37,
    lifeStageTone: "established urban adulthood",
    visualMaturity: "mature, composed, confident without performance",
    stylingAttitude: "quietly refined",
    socialEnergy: "self-contained, composed",
    bodyLanguageGuidance: [
      "Use grounded movement and restrained, intentional gestures.",
      "Let composure come from behavior rather than posture display.",
    ],
    performanceGuardrails: [
      "no power-woman stereotype",
      "no default executive role",
      "no performed authority",
      "no exaggerated confidence display",
    ],
    status: "ACTIVE",
  },
  {
    id: "age_38_42",
    label: "38–42｜松弛知性",
    ageMin: 38,
    ageMax: 42,
    lifeStageTone: "experienced and self-directed",
    visualMaturity: "mature, relaxed, intellectually composed",
    stylingAttitude: "quiet, considered, effortless",
    socialEnergy: "calm, self-contained",
    bodyLanguageGuidance: [
      "Use relaxed movement with clear personal boundaries.",
      "Keep gestures economical and self-directed.",
    ],
    performanceGuardrails: [
      "no literary performance",
      "no forced intellectual persona",
      "no cultivated elegance",
      "no automatic family or mother identity",
    ],
    status: "ACTIVE",
  },
  {
    id: "age_43_47",
    label: "43–47｜成熟生活",
    ageMin: 43,
    ageMax: 47,
    lifeStageTone: "mature lived-in urban life",
    visualMaturity: "settled, assured, naturally refined",
    stylingAttitude: "functional, elegant, understated",
    socialEnergy: "steady, grounded",
    bodyLanguageGuidance: [
      "Use steady, practical movement with natural weight and timing.",
      "Keep the body language fully age-appropriate without signaling limitation.",
    ],
    performanceGuardrails: [
      "no age-emphasis content",
      "no middle-age stereotype",
      "no default homemaker or mother role",
      "no assumed slower movement",
      "no conservative-dressing assumption",
    ],
    status: "ACTIVE",
  },
  {
    id: "age_48_55",
    label: "48–55｜从容成熟",
    ageMin: 48,
    ageMax: 55,
    lifeStageTone: "experienced, self-assured adulthood",
    visualMaturity: "mature, calm, naturally elegant",
    stylingAttitude: "timeless, restrained, confident",
    socialEnergy: "steady, composed",
    bodyLanguageGuidance: [
      "Use natural adult movement with stable timing and no implied limitation.",
      "Keep gestures relaxed, legible, and self-directed.",
    ],
    performanceGuardrails: [
      "no anti-aging framing",
      "no youthful-appearance goal",
      "no assumed slow movement",
      "no assumed physical limitation",
      "no wealthy-matriarch stereotype",
      "no automatic jewelry or luxury-accessory inference",
    ],
    status: "ACTIVE",
  },
];
