import type { ProductPromptAdapter } from "../productAdapter";
import type { ProductAdapterInput } from "../types";
import type { ShoeCategoryAdapter, ShoeAccuracyGuardSet, ShoeContentProfile, ShoeFieldDefinition, ShoeReferenceRequirements, ShoeShotPlanProfile } from "./shoeCategoryRegistry";
import type { BalletFlatShoeSpec, ShoeProductContext } from "./shoeProductTypes";
const defaultSpec: BalletFlatShoeSpec = { category:"balletFlat", productName:"ballet flat", subtype:"other", toeShape:"other", vampCoverage:"按参考图保持", toplineShape:"按参考图保持", ornament:"none", strapType:"none", heelLift:"按参考图保持", outsoleThickness:"按参考图保持", keyDetails:[] };
const specOf=(c:ShoeProductContext)=>({...defaultSpec,...(c.balletFlatSpec??{})});
export const balletFlatFieldSchema: ShoeFieldDefinition[] = ["productName","brandName","subtype","color","upperMaterial","finish","toeShape","vampCoverage","vampShape","toplineShape","toplineDepth","sideCut","bindingType","bindingWidth","elasticEdge","ornament","bowShape","bowSize","ornamentPlacement","strapType","strapPlacement","buckleShape","heelCounterHeight","heelLift","outsoleThickness","outsoleFlex","seamStructure","decorativeDetails","keyDetails"].map((key)=>({key,label:key,type:key==="keyDetails"?"textarea":"text",required:["productName","subtype","color","toeShape","vampCoverage","toplineShape","ornament","strapType","heelLift","outsoleThickness","upperMaterial","keyDetails"].includes(key)}));
export const balletFlatReferenceRequirements:ShoeReferenceRequirements={minCount:4,maxCount:6,requiredRoles:["primary","fullSide"],recommendedRoles:["front","top","rear","detail","material"]};
export const balletFlatShotPlanProfile:ShoeShotPlanProfile={supportedImageCounts:[1,3,5,8],supportsLifestyleSeries:true,supportsStudioSeries:true};
export const balletFlatAccuracyGuards:ShoeAccuracyGuardSet={structurePriorities:["toe shape","shallow vamp","topline","binding","side cut","bow or ornament","strap","heel lift","thin outsole","material"],requiresGroundedContact:true,requiresReferenceAccuracy:true};
const negatives=["changed topline depth","changed shallow-vamp coverage","added or removed bow","changed bow size","added or removed strap","changed strap count","invented buckle","changed binding width","thick athletic-shoe sole","loafer apron or horsebit","pump heel","boot shaft","slipper transformation","extreme collapse","exposed toes in a closed-toe flat","foot or shoe intersection","floating heel","duplicated shoes or feet"];
export const balletFlatContentProfile:ShoeContentProfile={productNouns:["ballet flat","Mary Jane flat","soft flat","芭蕾鞋","平底鞋"],structurePriorities:balletFlatAccuracyGuards.structurePriorities,lifestyleBenefits:["everyday styling","trouser, skirt, and dress coordination","low-profile proportion","work and weekend versatility"],forbiddenPrimaryTerms:["German trainer","sneaker","pump","boot shaft","loafer apron"]};
function createBalletFlatPromptAdapter(c:ShoeProductContext):ProductPromptAdapter{const s=specOf(c);const line=`Use uploaded ballet-flat references as the strict source. Preserve ${s.productName}, subtype ${s.subtype}, toe shape ${s.toeShape}, vamp coverage ${s.vampCoverage}, topline ${s.toplineShape}, binding, ornament ${s.ornament}, strap ${s.strapType}, heel lift ${s.heelLift}, thin outsole ${s.outsoleThickness}, material, color, and proportions.`;return{mode:"shoe",getDisplayName:()=>s.productName,isProductPresent:(i)=>i.imageType!=="非产品氛围图",buildProductLine:()=>line,buildAccuracyLines:()=>["Preserve the exact ballet-flat silhouette, toe geometry, shallow vamp coverage, topline opening, binding edge, side cut, heel counter, heel lift, outsole thinness, strap or ornament structure, material, color, finish, and proportions shown in the uploaded references."],buildVisibilityLines:()=>["Keep at least one ballet flat fully visible from toe to heel."],buildClippingLines:()=>["Keep foot, opening, binding, garment hem, flat, and floor physically separate; no toe clipping, opening cutting into the foot, or floating heel."],buildSceneControlLines:()=>["Use natural everyday movement: standing, slight weight shift, small step, side stance, or restrained seated pause; avoid running, jumping, high kick, extreme toe pointing, and slipper-like collapse."],buildCompositionLines:(i)=>i.scenePreference==="棚内上新拍摄"?[`Ballet-flat studio shot ${typeof i.studioLaunchShotIndex==="number"?i.studioLaunchShotIndex+1:"plan"} of 8: prove toe, shallow vamp, topline, binding, ornament or strap, heel lift, and thin outsole.`]:[],buildImageTypeLines:()=>["Ballet-flat identity: keep shallow vamp, topline, binding, side cut, bow or strap, heel lift, thin outsole, and material category-native."],buildActionSafetyLines:()=>["Foot-to-flat contact must be natural; no foot sliding out, no opening cutting into the foot, no collapse, no floating heel, and no duplicated feet."],buildNegativePhrases:()=>negatives,buildStylingBoundaryLines:()=>["Use cropped or straight trousers, midi skirts, dresses, relaxed tailoring, and intentional hosiery; keep the opening, binding, and ornament visible."],getProductSpecificQualityLines:()=>["Ballet-flat quality check: subtype, toe, vamp, topline, binding, ornament, strap, heel lift, outsole, and foot contact remain reference-accurate."]};}
export const balletFlatAdapter:ShoeCategoryAdapter={category:"balletFlat",status: "active",createPromptAdapter:createBalletFlatPromptAdapter,getFieldSchema:()=>balletFlatFieldSchema,getReferenceRequirements:()=>balletFlatReferenceRequirements,getShotPlanProfile:()=>balletFlatShotPlanProfile,getAccuracyGuards:()=>balletFlatAccuracyGuards,getNegativeRules:()=>negatives,getContentProfile:()=>balletFlatContentProfile};
