import type { ProductPromptAdapter } from "../productAdapter";
import type { ProductAdapterInput } from "../types";
import type { ShoeCategoryAdapter, ShoeAccuracyGuardSet, ShoeContentProfile, ShoeFieldDefinition, ShoeReferenceRequirements, ShoeShotPlanProfile } from "./shoeCategoryRegistry";
import type { LoaferShoeSpec, ShoeProductContext } from "./shoeProductTypes";

const defaultSpec: LoaferShoeSpec = { category: "loafer", productName: "loafer", subtype: "other", toeShape: "other", upperConstruction: "other", ornament: "none", heelHeight: "按参考图保持", keyDetails: [] };
const specOf = (c: ShoeProductContext) => ({ ...defaultSpec, ...(c.loaferSpec ?? {}) });
export const loaferFieldSchema: ShoeFieldDefinition[] = ["productName","brandName","subtype","color","upperMaterial","finish","toeShape","upperConstruction","apronShape","apronSeam","vampHeight","instepPanelShape","ornament","saddleShape","pennySlotShape","hardwareShape","hardwareFinish","tasselCount","toplineShape","toplineDepth","heelHeight","outsoleThickness","outsoleProfile","weltEdge","treadProfile","seamStructure","decorativeDetails","keyDetails"].map((key) => ({ key, label: key, type: key === "keyDetails" ? "textarea" : "text", required: ["productName","subtype","color","toeShape","upperConstruction","ornament","heelHeight","upperMaterial","keyDetails"].includes(key) }));
export const loaferReferenceRequirements: ShoeReferenceRequirements = { minCount: 4, maxCount: 6, requiredRoles: ["primary", "fullSide"], recommendedRoles: ["front","top","rear","detail","material"] };
export const loaferShotPlanProfile: ShoeShotPlanProfile = { supportedImageCounts: [1,3,5,8], supportsLifestyleSeries: true, supportsStudioSeries: true };
export const loaferAccuracyGuards: ShoeAccuracyGuardSet = { structurePriorities: ["toe shape","apron","apron seam","vamp","saddle","penny slot","ornament","topline","heel","welt","outsole","tread","material"], requiresGroundedContact: true, requiresReferenceAccuracy: true };
const negatives = ["changed apron shape","missing apron seam","added or removed penny saddle","changed penny slot","invented horsebit","changed hardware finish","added or removed tassel","changed tassel count","fringe unless referenced","athletic-footwear closure logic","thick running-shoe sole","pump transformation","ballet-flat transformation","boot shaft","changed topline","invented tread","foot or shoe intersection","floating heel","duplicated shoes or feet"];
export const loaferContentProfile: ShoeContentProfile = { productNouns: ["loafer","penny loafer","horsebit loafer","tassel loafer","乐福鞋"], structurePriorities: loaferAccuracyGuards.structurePriorities, lifestyleBenefits: ["work and weekend versatility","smart-casual balance","trouser and skirt coordination"], forbiddenPrimaryTerms: ["German trainer","sneaker","pump","boot shaft","ballet flat"] };
function createLoaferPromptAdapter(c: ShoeProductContext): ProductPromptAdapter { const s = specOf(c); const line = `Use uploaded loafer references as the strict source. Preserve ${s.productName}, subtype ${s.subtype}, toe shape ${s.toeShape}, ${s.upperConstruction} construction, apron/vamp, saddle or ornament ${s.ornament}, topline, heel height ${s.heelHeight}, outsole, welt, material, color, and proportions.`; return { mode:"shoe", getDisplayName:()=>s.productName, isProductPresent:(i)=>i.imageType !== "非产品氛围图", buildProductLine:()=>line, buildAccuracyLines:()=>["Preserve the exact loafer silhouette, toe geometry, apron or vamp construction, saddle and ornament structure, topline opening, heel counter, heel height, outsole thickness, welt profile, material, color, finish, and proportions shown in the uploaded references."], buildVisibilityLines:()=>["Keep at least one loafer fully visible from toe to heel."], buildClippingLines:()=>["Keep foot, instep, vamp, topline, garment hem, loafer, and floor physically separate; no clipping or floating heel."], buildSceneControlLines:()=>["Use refined smart-casual movement: standing, small step, side stance, or restrained seated pause; avoid running, jumping, deep squat, and exaggerated athletic flex."], buildCompositionLines:(i)=>i.scenePreference === "棚内上新拍摄" ? [`Loafer studio shot ${typeof i.studioLaunchShotIndex === "number" ? i.studioLaunchShotIndex + 1 : "plan"} of 8: prove toe, apron, vamp, ornament, heel, welt, outsole, and tread.`] : [], buildImageTypeLines:()=>["Loafer identity: keep apron, saddle, ornament, topline, heel, welt, outsole, and material category-native."], buildActionSafetyLines:()=>["Foot-to-loafer contact must be natural at the instep; no foot through vamp, floating heel, or duplicated feet."], buildNegativePhrases:()=>negatives, buildStylingBoundaryLines:()=>["Use cropped or straight trousers, midi skirts, dresses, suits, and intentional refined socks; keep apron and ornament visible."], getProductSpecificQualityLines:()=>["Loafer quality check: subtype, apron, ornament, topline, heel, welt, outsole, and foot contact remain reference-accurate."] }; }
export const loaferAdapter: ShoeCategoryAdapter = { category:"loafer", status: "active", createPromptAdapter:createLoaferPromptAdapter, getFieldSchema:()=>loaferFieldSchema, getReferenceRequirements:()=>loaferReferenceRequirements, getShotPlanProfile:()=>loaferShotPlanProfile, getAccuracyGuards:()=>loaferAccuracyGuards, getNegativeRules:()=>negatives, getContentProfile:()=>loaferContentProfile };
