import type { ProductPromptAdapter } from "../productAdapter";
import type { ShoeCategoryAdapter, ShoeAccuracyGuardSet, ShoeContentProfile, ShoeFieldDefinition, ShoeReferenceRequirements, ShoeShotPlanProfile } from "./shoeCategoryRegistry";
import type { MuleShoeSpec, ShoeProductContext } from "./shoeProductTypes";
const d:MuleShoeSpec={category:"mule",productName:"mule",subtype:"other",toeType:"other",vampCoverage:"按参考图保持",heelType:"other",heelHeight:"按参考图保持",keyDetails:[]}; const spec=(c:ShoeProductContext)=>({...d,...(c.muleSpec??{})});
export const muleFieldSchema:ShoeFieldDefinition[]=["productName","brandName","subtype","color","upperMaterial","finish","toeType","toeShape","toeOpeningShape","vampCoverage","vampShape","throatShape","toplineShape","sideCut","backlessEdgeShape","footInsertionDepth","heelExposure","heelOverhangRelation","strapType","strapPlacement","ornamentType","ornamentPlacement","hardwareShape","heelType","heelHeight","heelPlacement","outsoleThickness","platformHeight","treadProfile","decorativeDetails","keyDetails"].map(key=>({key,label:key,type:key==="keyDetails"?"textarea":"text",required:["productName","subtype","color","toeType","vampCoverage","heelType","heelHeight","upperMaterial","keyDetails"].includes(key)}));
export const muleReferenceRequirements:ShoeReferenceRequirements={minCount:4,maxCount:6,requiredRoles:["primary","fullSide"],recommendedRoles:["front","rear","top","detail","material"]}; export const muleShotPlanProfile:ShoeShotPlanProfile={supportedImageCounts:[1,3,5,8],supportsLifestyleSeries:true,supportsStudioSeries:true};
export const muleAccuracyGuards:ShoeAccuracyGuardSet={structurePriorities:["toe opening","vamp coverage","throat","topline","backless edge","insertion depth","heel exposure","heel","outsole","platform","material"],requiresGroundedContact:true,requiresReferenceAccuracy:true}; const negatives=["added heel counter","changed backless edge","changed heel exposure","changed insertion depth","pump transformation","sandal ankle strap unless referenced","loafer transformation unless loafer-mule subtype","ballet-flat transformation","slipper collapse","changed toe or vamp coverage","changed heel","changed platform","foot sliding forward","floating heel","foot or shoe intersection","duplicated feet or shoes"];
export const muleContentProfile:ShoeContentProfile={productNouns:["mule","closed-toe mule","open-toe mule","heeled mule","flat mule","穆勒鞋"],structurePriorities:muleAccuracyGuards.structurePriorities,lifestyleBenefits:["easy styling","trouser, skirt, and dress coordination","work and social versatility","backless proportion"],forbiddenPrimaryTerms:["sandal","pump","boot shaft","German trainer","sneaker"]};
function create(c:ShoeProductContext):ProductPromptAdapter{const s=spec(c);const line=`Use uploaded mule references as the strict source. Preserve ${s.productName}, subtype ${s.subtype}, toe type ${s.toeType}, vamp coverage ${s.vampCoverage}, throat and topline, backless edge, insertion depth, heel exposure, heel ${s.heelType} ${s.heelHeight}, outsole, material, color, and proportions.`;return{mode:"shoe",getDisplayName:()=>s.productName,isProductPresent:i=>i.imageType!=="非产品氛围图",buildProductLine:()=>line,buildAccuracyLines:()=>["Preserve the exact mule silhouette, toe geometry or opening, vamp coverage, throat and topline shape, side cut, backless edge, foot-insertion depth, heel-exposure proportion, heel geometry, outsole thickness, platform height, material, color, finish, and proportions shown in the uploaded references."],buildVisibilityLines:()=>["Keep at least one mule fully visible from toe or opening to heel."],buildClippingLines:()=>["Keep foot, vamp, opening, backless edge, heel exposure, garment hem, mule, and floor physically separate; no sliding foot, floating heel, or intersection."],buildSceneControlLines:()=>["Use relaxed movement: standing, slight weight shift, small step, side stance, or restrained seated pause; avoid running, jumping, long stride, and shoe rotation under the foot."],buildCompositionLines:i=>i.scenePreference==="棚内上新拍摄"?[`Mule studio shot ${typeof i.studioLaunchShotIndex==="number"?i.studioLaunchShotIndex+1:"plan"} of 8: prove toe, vamp, backless edge, heel exposure, heel, outsole, and ornament.`]:[],buildImageTypeLines:()=>["Mule identity: preserve backless structure, vamp coverage, opening, insertion depth, heel exposure, heel, platform, and outsole without turning it into a sandal or pump."],buildActionSafetyLines:()=>["Insert the foot to the referenced depth; heel remains naturally exposed, not floating far above the sole, and the foot must not slide forward."],buildNegativePhrases:()=>negatives,buildStylingBoundaryLines:()=>["Use cropped or straight trousers, midi skirts, dresses, tailored shorts, relaxed tailoring, or refined evening styling; keep backless edge and heel exposure visible."],getProductSpecificQualityLines:()=>["Mule quality check: toe, vamp, backless edge, insertion depth, heel exposure, outsole, and foot contact remain reference-accurate."]};}
export const muleAdapter:ShoeCategoryAdapter={category:"mule",status: "active",createPromptAdapter:create,getFieldSchema:()=>muleFieldSchema,getReferenceRequirements:()=>muleReferenceRequirements,getShotPlanProfile:()=>muleShotPlanProfile,getAccuracyGuards:()=>muleAccuracyGuards,getNegativeRules:()=>negatives,getContentProfile:()=>muleContentProfile};
