import type { ProductPromptAdapter } from "../productAdapter";
import type { ShoeCategoryAdapter, ShoeAccuracyGuardSet, ShoeContentProfile, ShoeFieldDefinition, ShoeReferenceRequirements, ShoeShotPlanProfile } from "./shoeCategoryRegistry";
import type { SandalShoeSpec, ShoeProductContext } from "./shoeProductTypes";
const d:SandalShoeSpec={category:"sandal",productName:"sandal",subtype:"other",toeType:"other",heelType:"other",heelHeight:"按参考图保持",keyDetails:[]}; const spec=(c:ShoeProductContext)=>({...d,...(c.sandalSpec??{})});
export const sandalFieldSchema:ShoeFieldDefinition[]=["productName","brandName","subtype","color","upperMaterial","finish","toeType","toeOpeningShape","forefootStrapCount","forefootStrapWidth","forefootStrapPlacement","vampStrapShape","instepStrap","ankleStrap","heelStrap","slingbackShape","tBarShape","toePostShape","buckleCount","bucklePosition","hardwareShape","hardwareFinish","footbedShape","heelType","heelHeight","heelPlacement","outsoleThickness","platformHeight","treadProfile","decorativeDetails","keyDetails"].map(key=>({key,label:key,type:key==="keyDetails"?"textarea":"text",required:["productName","subtype","color","toeType","heelType","heelHeight","upperMaterial","keyDetails"].includes(key)}));
export const sandalReferenceRequirements:ShoeReferenceRequirements={minCount:4,maxCount:6,requiredRoles:["primary","fullSide"],recommendedRoles:["front","rear","top","detail","material"]}; export const sandalShotPlanProfile:ShoeShotPlanProfile={supportedImageCounts:[1,3,5,8],supportsLifestyleSeries:true,supportsStudioSeries:true};
export const sandalAccuracyGuards:ShoeAccuracyGuardSet={structurePriorities:["toe opening","strap count","strap placement","ankle strap","heel strap","buckle","footbed","heel","outsole","platform","material"],requiresGroundedContact:true,requiresReferenceAccuracy:true}; const negatives=["changed toe opening","missing or extra straps","changed strap crossing order","strap cutting through foot","missing heel strap","invented T-bar or toe post","changed buckle count","changed heel","pump transformation","mule transformation","ballet-flat transformation","sneaker sole","foot or strap intersection","toes beyond footbed","floating heel","duplicated toes or feet"];
export const sandalContentProfile:ShoeContentProfile={productNouns:["sandal","ankle-strap sandal","slingback sandal","strappy sandal","凉鞋"],structurePriorities:sandalAccuracyGuards.structurePriorities,lifestyleBenefits:["warm-weather styling","dress and trouser coordination","social versatility","strap and heel balance"],forbiddenPrimaryTerms:["mule","pump","boot shaft","German trainer","sneaker"]};
function create(c:ShoeProductContext):ProductPromptAdapter{const s=spec(c);const line=`Use uploaded sandal references as the strict source. Preserve ${s.productName}, subtype ${s.subtype}, toe type ${s.toeType}, strap layout and count, ankle or heel strap, buckle, heel ${s.heelType} ${s.heelHeight}, outsole, material, color, and proportions.`;return{mode:"shoe",getDisplayName:()=>s.productName,isProductPresent:i=>i.imageType!=="非产品氛围图",buildProductLine:()=>line,buildAccuracyLines:()=>["Preserve the exact sandal subtype, toe opening, strap count, strap width, strap placement and crossing order, ankle or heel strap construction, buckle and hardware geometry, footbed shape, heel geometry, outsole thickness, platform height, material, color, finish, and proportions shown in the uploaded references."],buildVisibilityLines:()=>["Keep at least one sandal fully readable from toe opening to heel."],buildClippingLines:()=>["Keep toes, footbed, straps, ankle, heel strap, garment hem, and floor physically separate; no strap cutting through skin or foot intersection."],buildSceneControlLines:()=>["Use natural warm-weather movement: standing, slight weight shift, small step, side stance, or restrained seated pause; avoid running, jumping, long stride, and unnatural toe gripping."],buildCompositionLines:i=>i.scenePreference==="棚内上新拍摄"?[`Sandal studio shot ${typeof i.studioLaunchShotIndex==="number"?i.studioLaunchShotIndex+1:"plan"} of 8: prove toe opening, straps, buckle, heel, platform, outsole, and tread.`]:[],buildImageTypeLines:()=>["Sandal identity: keep toe exposure, strap hierarchy, ankle or heel strap, footbed, heel, platform, and outsole category-native."],buildActionSafetyLines:()=>["Toes must align naturally with the opening and remain seated on the footbed; no missing or duplicated toes, floating heel, or sliding foot."],buildNegativePhrases:()=>negatives,buildStylingBoundaryLines:()=>["Use cropped trousers, midi skirts, dresses, tailored shorts, light suits, or refined event styling; keep toes, straps, and heel visible."],getProductSpecificQualityLines:()=>["Sandal quality check: toe opening, strap layout, heel/ankle structure, footbed, outsole, and foot contact remain reference-accurate."]};}
export const sandalAdapter:ShoeCategoryAdapter={category:"sandal",status: "active",createPromptAdapter:create,getFieldSchema:()=>sandalFieldSchema,getReferenceRequirements:()=>sandalReferenceRequirements,getShotPlanProfile:()=>sandalShotPlanProfile,getAccuracyGuards:()=>sandalAccuracyGuards,getNegativeRules:()=>negatives,getContentProfile:()=>sandalContentProfile};
