import type {
  CommercialEndingGrammar,
  CommercialEndingGrammarId,
  CommercialEventShot,
} from "./types";
import type { CommercialIntentId } from "../types";

export type CommercialEventSpineTemplate = {
  intent: CommercialIntentId;
  centralEvent: string;
  shots: Array<Omit<CommercialEventShot, "shotIndex" | "shotRole">>;
  endingGrammarId: CommercialEndingGrammarId;
};

export const COMMERCIAL_ENDING_GRAMMARS: Record<CommercialEndingGrammarId, CommercialEndingGrammar> = {
  CONTINUED_SPATIAL_MOVEMENT: {
    id: "CONTINUED_SPATIAL_MOVEMENT",
    label: "Continued Spatial Movement",
    line: "The subject continues beyond the established city point while the camera stays with the place she has just crossed.",
    resolves: "The urban route remains open while the film's spatial idea completes.",
    newGrammarGuard: "Do not introduce a new destination, camera grammar, or product reveal after the established route point.",
  },
  TRANSITION_INTO_LIVED_USE: {
    id: "TRANSITION_INTO_LIVED_USE",
    label: "Transition Into Lived Use",
    line: "The preparation resolves into the first lived movement outside the private space.",
    resolves: "The styling decision is complete and has entered real use.",
    newGrammarGuard: "Do not return to wardrobe preparation or add a new styling objective.",
  },
  STILLNESS_AND_ROOM_CONTINUES: {
    id: "STILLNESS_AND_ROOM_CONTINUES",
    label: "Stillness And Room Continues",
    line: "The person settles while the room, light, and quiet environment continue unchanged.",
    resolves: "The private perceptual arc settles without another action or product explanation.",
    newGrammarGuard: "Do not add movement, a new object, or a new location after the stillness is established.",
  },
  COMPLETION_AND_QUIET_DEPARTURE: {
    id: "COMPLETION_AND_QUIET_DEPARTURE",
    label: "Completion And Quiet Departure",
    line: "The final action completes and the person becomes ready to leave the preparation space.",
    resolves: "The observed craft relationship returns to the complete worn look.",
    newGrammarGuard: "Do not introduce a second product investigation or another detail after completion.",
  },
  ARRIVAL_SETTLES: {
    id: "ARRIVAL_SETTLES",
    label: "Arrival Settles",
    line: "The arrival becomes a settled state, with the surrounding place continuing naturally around her.",
    resolves: "The approach, entry, and integration are complete.",
    newGrammarGuard: "Do not add another destination or restart movement after the arrival has settled.",
  },
};

export const COMMERCIAL_EVENT_SPINE_TEMPLATES: Record<
  CommercialIntentId,
  CommercialEventSpineTemplate
> = {
  URBAN_MOTION: {
    intent: "URBAN_MOTION",
    centralEvent: "A believable urban route changes spatial condition while the same person and footwear continue through it.",
    shots: [
      {
        eventKind: "CITY_ENTRY",
        whatHappens: "The person crosses from one urban plane into the next without breaking pace.",
        whyItHappens: "The route is already in motion and the camera begins inside that movement.",
        whatChanges: "The film moves from a held urban context into active spatial transition.",
        actionClass: "transition",
        causalFromPrevious: "The route establishes the direction that the following movement must continue.",
        framingHint: "partial foreground city frame with the person entering the route",
        perceptualTarget: "near-to-far depth change",
        durationSeconds: 3.1,
        durationRationale: "Enough time to establish route direction without holding before movement.",
      },
      {
        eventKind: "ROUTE_CONTINUATION",
        whatHappens: "She keeps the same route into one changed street condition at the curb.",
        whyItHappens: "The first crossing creates a believable next segment in the same journey.",
        whatChanges: "The viewer understands that the route, not the pose, is carrying continuity.",
        actionClass: "walking",
        causalFromPrevious: "A continued step inherits the direction established at the entry.",
        framingHint: "full figure at a three-quarter route angle",
        perceptualTarget: "movement held inside changing city depth",
        durationSeconds: 2.6,
        durationRationale: "A shorter middle beat maintains moving rhythm.",
      },
      {
        eventKind: "GROUND_RELATION_CHANGE",
        whatHappens: "She takes one short step onto a changed surface and lets the leading foot settle.",
        whyItHappens: "The changed surface makes the body resolve a new ground relationship.",
        whatChanges: "The product is noticed through actual weight and ground contact rather than presentation.",
        actionClass: "on-foot",
        causalFromPrevious: "The continued route creates the exact moment where surface and stride can be observed.",
        framingHint: "lower-body movement inside the broader city frame",
        perceptualTarget: "compressed ground-level observation",
        durationSeconds: 1.8,
        durationRationale: "A brief detail after the larger movement prevents a beauty-insert rhythm.",
        productDetailRelationship: "footwear-stride-ground relationship",
      },
      {
        eventKind: "URBAN_PAUSE",
        whatHappens: "She reaches a natural pause point and lets her weight settle without posing.",
        whyItHappens: "The route itself creates a believable moment to slow into a grounded stop.",
        whatChanges: "The worn product and complete outfit become clear through the pause.",
        actionClass: "turning",
        causalFromPrevious: "The step resolves into a grounded pause before the next movement.",
        framingHint: "medium-full worn-product observation at the pause point",
        perceptualTarget: "human-scale pause inside the street",
        durationSeconds: 3.3,
        durationRationale: "Hero comprehension needs enough time to read the worn context.",
      },
      {
        eventKind: "ROUTE_RELEASE",
        whatHappens: "She continues beyond the pause point while the camera remains with the place she crossed.",
        whyItHappens: "The route remains open and the film resolves through continuation rather than a product-only ending.",
        whatChanges: "The viewer leaves with the sense that the city movement continues after the film.",
        actionClass: "environment-response",
        causalFromPrevious: "The pause resolves into the next ordinary movement.",
        framingHint: "held environmental frame with the subject leaving the deeper plane",
        perceptualTarget: "camera stays, subject continues",
        durationSeconds: 4.2,
        durationRationale: "Release needs breathing room to hold the place after the person moves on.",
      },
    ],
    endingGrammarId: "CONTINUED_SPATIAL_MOVEMENT",
  },
  DAILY_STYLING: {
    intent: "DAILY_STYLING",
    centralEvent: "A private styling decision is completed and then tested in the first real movement of the day.",
    shots: [
      {
        eventKind: "WARDROBE_DECISION",
        whatHappens: "She completes one useful wardrobe task that resolves the look.",
        whyItHappens: "The day is beginning and the outfit needs one last practical decision.",
        whatChanges: "The private preparation state becomes a complete styling state.",
        actionClass: "garment-task",
        causalFromPrevious: "The preparation moment establishes the outfit state that the rest of the film must carry.",
        framingHint: "upper-body and garment framing before the footwear is revealed",
        perceptualTarget: "private detail in a lived dressing area",
        durationSeconds: 3.7,
        durationRationale: "The preparation needs enough time to feel task-led rather than decorative.",
      },
      {
        eventKind: "THRESHOLD_TEST",
        whatHappens: "She crosses the doorway threshold and the completed look enters real movement.",
        whyItHappens: "Preparation naturally leads into leaving the private space.",
        whatChanges: "The styling leaves the mirror context and becomes everyday use.",
        actionClass: "walking",
        causalFromPrevious: "The completed look enables the first step outside.",
        framingHint: "full figure through a doorway with the person crossing",
        perceptualTarget: "private-to-public spatial change",
        durationSeconds: 2.4,
        durationRationale: "The threshold is a transition beat, so it stays concise.",
      },
      {
        eventKind: "GARMENT_FOOT_RELATION",
        whatHappens: "She completes the step and lets the finished hem, ankle, and footwear relationship become visible.",
        whyItHappens: "The threshold crossing makes the worn relationship visible without a pose.",
        whatChanges: "The viewer understands the complete styling as a physical fact.",
        actionClass: "on-foot",
        causalFromPrevious: "The crossing creates the natural lower-body observation.",
        framingHint: "medium-lower body inside the doorway action",
        perceptualTarget: "worn relationship inside movement",
        durationSeconds: 1.8,
        durationRationale: "A short confirmation avoids turning the detail into a catalog insert.",
        productDetailRelationship: "garment-ankle-footwear relationship",
      },
      {
        eventKind: "READY_TO_MOVE",
        whatHappens: "She reaches the outside edge, stops naturally, and lets the completed look settle.",
        whyItHappens: "The first step outside creates a believable pause before the day continues.",
        whatChanges: "Preparation becomes confidence in lived use.",
        actionClass: "standing",
        causalFromPrevious: "The crossing resolves into a grounded ready state.",
        framingHint: "medium-full outfit and worn-product observation",
        perceptualTarget: "settled human-scale read",
        durationSeconds: 3.6,
        durationRationale: "The hero needs enough still time to complete the commercial read.",
      },
      {
        eventKind: "LIVED_USE",
        whatHappens: "She moves into the first ordinary street step with the styling already resolved.",
        whyItHappens: "The completed look has entered the day and no further decision is needed.",
        whatChanges: "The film leaves with the product already integrated into daily life.",
        actionClass: "transition",
        causalFromPrevious: "The ready state becomes lived movement.",
        framingHint: "medium environmental exit with no return to preparation",
        perceptualTarget: "outfit continuity after the threshold",
        durationSeconds: 3.5,
        durationRationale: "Release resolves through movement while keeping enough room for aftertaste.",
      },
    ],
    endingGrammarId: "TRANSITION_INTO_LIVED_USE",
  },
  QUIET_LUXURY: {
    intent: "QUIET_LUXURY",
    centralEvent: "A private pause makes material and proportion perceptible through stillness rather than explanation.",
    shots: [
      {
        eventKind: "PRIVATE_STATE",
        whatHappens: "She stands by the window with most of her weight settled on the rear leg.",
        whyItHappens: "The film enters the room before it asks the viewer to notice the product.",
        whatChanges: "The viewer understands the private atmosphere and human presence.",
        actionClass: "standing",
        causalFromPrevious: "The opening stillness establishes the room and the person's self-directed state.",
        framingHint: "partial interior frame with foreground occlusion",
        perceptualTarget: "privacy before object recognition",
        durationSeconds: 3.9,
        durationRationale: "The human atmosphere must exist before the product is read.",
      },
      {
        eventKind: "RESTRAINED_SHIFT",
        whatHappens: "She makes one small standing adjustment that changes the body line.",
        whyItHappens: "The private pause naturally produces a small change in weight distribution.",
        whatChanges: "The silhouette and outfit become visible through a real adjustment.",
        actionClass: "seated",
        causalFromPrevious: "The private stillness creates the need for one restrained physical shift.",
        framingHint: "medium body line with room and texture visible",
        perceptualTarget: "quiet human change",
        durationSeconds: 2.8,
        durationRationale: "A restrained middle beat should not compete with the hero.",
      },
      {
        eventKind: "MATERIAL_PAUSE",
        whatHappens: "She holds the pause and lets her weight settle through the ankle and heel while side light defines the lower silhouette.",
        whyItHappens: "The body shift creates a natural moment where one material relationship can be seen.",
        whatChanges: "The product becomes perceptible without a presentation gesture.",
        actionClass: "on-foot",
        causalFromPrevious: "The body change opens one brief opportunity for material perception.",
        framingHint: "medium composition with the product relationship inside the body frame",
        perceptualTarget: "material presence without packshot",
        durationSeconds: 1.5,
        durationRationale: "A very short material beat protects the quiet rhythm.",
        productDetailRelationship: "proportion and natural side-light relationship",
      },
      {
        eventKind: "PRODUCT_RECOGNITION",
        whatHappens: "She shifts her weight once and holds the complete worn line in the private light.",
        whyItHappens: "The earlier pause and material observation culminate in a completed understanding.",
        whatChanges: "The product is understood as part of the private life, not as a separate object.",
        actionClass: "standing",
        causalFromPrevious: "The material beat resolves into the complete worn context.",
        framingHint: "medium-full still observation with light defining material",
        perceptualTarget: "quiet worn clarity",
        durationSeconds: 3.5,
        durationRationale: "The hero needs a stable final comprehension beat.",
      },
      {
        eventKind: "ROOM_CONTINUES",
        whatHappens: "The person remains still while the room and light continue around her.",
        whyItHappens: "The film resolves through atmosphere rather than another action.",
        whatChanges: "The commercial ends in a held state instead of a new event.",
        actionClass: "environment-response",
        causalFromPrevious: "The recognition resolves into stillness and environmental continuation.",
        framingHint: "held room composition with no new subject action",
        perceptualTarget: "environmental aftertaste",
        durationSeconds: 3.3,
        durationRationale: "Release needs breathing room without introducing another beat.",
      },
    ],
    endingGrammarId: "STILLNESS_AND_ROOM_CONTINUES",
  },
  PRODUCT_CRAFT: {
    intent: "PRODUCT_CRAFT",
    centralEvent: "A preparation task creates a natural opportunity to understand one externally referenced product relationship.",
    shots: [
      {
        eventKind: "PREPARATION_CONTEXT",
        whatHappens: "She works through one ordinary preparation task that establishes the dressing context.",
        whyItHappens: "The task gives the camera a real reason to observe without posing.",
        whatChanges: "The film moves from a general preparation state into focused readiness.",
        actionClass: "garment-task",
        causalFromPrevious: "The preparation task creates the physical state in which a detail can appear.",
        framingHint: "environmental work-surface frame with the person at partial scale",
        perceptualTarget: "task before product",
        durationSeconds: 3.3,
        durationRationale: "The task needs enough time to remain causal.",
      },
      {
        eventKind: "WEAR_TRANSITION",
        whatHappens: "She stands from the preparation position and takes one small step with the product already worn.",
        whyItHappens: "The preparation task has produced a real body state that can now move.",
        whatChanges: "The product is seen in practical use rather than as an isolated object.",
        actionClass: "standing",
        causalFromPrevious: "Readiness turns into the first practical movement.",
        framingHint: "medium worn-product frame inside the room",
        perceptualTarget: "human-scale use",
        durationSeconds: 2.5,
        durationRationale: "The transition should be concise before the detail observation.",
      },
      {
        eventKind: "EXTERNAL_DETAIL_SELECTION",
        whatHappens: "She shifts her weight onto the leading foot and lets the trouser hem settle around the ankle.",
        productDetailRelationship: "surface",
        whyItHappens: "The prior movement exposes the selected reference-supported product relationship.",
        whatChanges: "The viewer notices one product relationship without AURA inventing its physical specifics.",
        actionClass: "on-foot",
        causalFromPrevious: "The practical movement makes the detail physically observable.",
        framingHint: "medium human frame containing the selected product relationship, not a default full-shoe close-up",
        perceptualTarget: "deferred external detail selection",
        durationSeconds: 1.7,
        durationRationale: "A short detail protects the film from becoming a product insert.",
      },
      {
        eventKind: "USE_CONFIRMATION",
        whatHappens: "Her weight settles through one small practical move, allowing the relationship to be understood in use.",
        whyItHappens: "A grounded action confirms the detail inside real movement.",
        whatChanges: "The observed relationship becomes part of the complete worn state.",
        actionClass: "standing",
        causalFromPrevious: "The detail resolves back into the complete human use.",
        framingHint: "medium-full worn context with the person in the frame",
        perceptualTarget: "detail returning to whole",
        durationSeconds: 3.5,
        durationRationale: "Hero comprehension requires the full human context.",
      },
      {
        eventKind: "QUIET_COMPLETION",
        whatHappens: "The action completes and she becomes ready to leave the preparation space.",
        whyItHappens: "The task has reached a stable conclusion.",
        whatChanges: "The film ends in readiness rather than another investigation.",
        actionClass: "transition",
        causalFromPrevious: "The grounded confirmation resolves into a quiet departure.",
        framingHint: "medium completion frame that holds the prepared state",
        perceptualTarget: "completion without another product angle",
        durationSeconds: 4.0,
        durationRationale: "Completion needs enough time to feel resolved rather than cut short.",
      },
    ],
    endingGrammarId: "COMPLETION_AND_QUIET_DEPARTURE",
  },
  NEW_ARRIVAL: {
    intent: "NEW_ARRIVAL",
    centralEvent: "An approach resolves into arrival and the product becomes part of the settled place.",
    shots: [
      {
        eventKind: "APPROACH",
        whatHappens: "She approaches a destination through a believable adjacent space.",
        whyItHappens: "The film begins with the movement toward arrival, not with a product introduction.",
        whatChanges: "The viewer understands the destination and the approach direction.",
        actionClass: "walking",
        causalFromPrevious: "The approach establishes the spatial direction of the arrival.",
        framingHint: "wide arrival frame with the subject entering from a believable edge",
        perceptualTarget: "approach depth",
        durationSeconds: 3.4,
        durationRationale: "Approach needs enough time to establish the destination.",
      },
      {
        eventKind: "THRESHOLD",
        whatHappens: "She reaches the destination threshold and makes the final physical adjustment to enter.",
        whyItHappens: "The approach has created a real crossing point.",
        whatChanges: "Movement becomes entry rather than travel.",
        actionClass: "transition",
        causalFromPrevious: "The approach resolves into the threshold crossing.",
        framingHint: "medium threshold frame with foreground spatial depth",
        perceptualTarget: "entry transition",
        durationSeconds: 2.3,
        durationRationale: "Threshold crossing is a transition beat and stays concise.",
      },
      {
        eventKind: "ARRIVAL_GROUNDING",
        whatHappens: "She feels the arrival surface through one real step and a settled weight change.",
        whyItHappens: "The threshold creates a natural point of contact with the new place.",
        whatChanges: "The product becomes part of the arrival rather than an object being announced.",
        actionClass: "on-foot",
        causalFromPrevious: "The entry produces the grounded contact that follows.",
        framingHint: "medium-lower arrival frame with the place visible",
        perceptualTarget: "arrival weight",
        durationSeconds: 1.6,
        durationRationale: "A brief grounded detail keeps the arrival moving toward settlement.",
        productDetailRelationship: "threshold-arrival surface-stop relationship",
      },
      {
        eventKind: "SETTLING",
        whatHappens: "She settles into the destination and the complete worn state becomes clear.",
        whyItHappens: "The arrival has completed and the body can resolve.",
        whatChanges: "The viewer understands how the product belongs to this place.",
        actionClass: "standing",
        causalFromPrevious: "The grounded arrival becomes a settled state.",
        framingHint: "medium-full settled composition with the destination visible",
        perceptualTarget: "settled worn context",
        durationSeconds: 3.7,
        durationRationale: "Hero comprehension needs the full arrival context.",
      },
      {
        eventKind: "ARRIVAL_ENVIRONMENT",
        whatHappens: "The destination continues around her while she remains settled in the arrival space.",
        whyItHappens: "The film resolves by showing that arrival has become part of the place.",
        whatChanges: "The commercial ends in an integrated state rather than another movement.",
        actionClass: "environment-response",
        causalFromPrevious: "The settled state releases into the continuing environment.",
        framingHint: "held arrival composition with no new route",
        perceptualTarget: "arrival becomes place",
        durationSeconds: 4.0,
        durationRationale: "Release needs breathing room to settle the arrival.",
      },
    ],
    endingGrammarId: "ARRIVAL_SETTLES",
  },
};
