import { NON_PRODUCT_ATMOSPHERE_SCENES } from "../data/nonProductAtmosphereSceneLines";
import type { AtmosphereSeasonId, AtmosphereSpatialType, ProductPresenceMode, SeasonSemanticProfile } from "./seasonSemanticProfiles";

export const ATMOSPHERE_SCENE_ARCHETYPE_IDS = [
  "ENTRYWAY_DEPARTURE", "ENTRYWAY_ARRIVAL", "WARDROBE_PREPARATION", "WINDOW_READING",
  "WORKTABLE_PAUSE", "RETURN_HOME_TABLE", "MARKET_RETURN_KITCHEN", "CAFE_FRONT",
  "CAFE_INTERIOR", "BOOKSTORE_MAGAZINE", "HOTEL_STAY", "RESIDENTIAL_TRANSITION",
  "CITY_TRANSIT", "MATERIAL_LIGHT_SPACE"
] as const;

export type AtmosphereSceneArchetypeId = (typeof ATMOSPHERE_SCENE_ARCHETYPE_IDS)[number];
export type AtmosphereFallbackReason = "unknown_legacy_scene" | "season_incompatible_scene" | "no_compatible_variant" | "explicit_material_light_space";
export type AtmosphereMigrationStatus = "exact" | "normalized" | "merged" | "fallback";

export type AtmosphereSceneArchetype = {
  id: AtmosphereSceneArchetypeId;
  label: string;
  locationLock: string;
  spatialType: AtmosphereSpatialType;
  allowsWardrobeTrace: boolean;
  preferredProductPresenceModes: ProductPresenceMode[];
  requiredSpatialCues: string[];
  forbiddenSpatialCues: string[];
  compositionCue: string;
  dominantPlane: "wall" | "floor" | "window" | "table" | "doorway";
  cameraHeight: "low" | "eye_level" | "slightly_high";
  depthPattern: "flat" | "layered" | "corridor" | "foreground_obstruction";
  dominantObject: string;
};

export type AtmosphereSceneVariant = {
  id: string;
  archetypeId: AtmosphereSceneArchetypeId;
  label: string;
  description: string;
  compatibleSeasons: "all" | AtmosphereSeasonId[];
  primaryTracePool: string[];
  supportingObjectPool: string[];
  spatialCuePool: string[];
  timeOfDayPool: string[];
  compositionCuePool: string[];
  allowsWardrobeTrace: boolean;
  wardrobeTracePool: string[];
  preferredProductPresenceModes: ProductPresenceMode[];
  conflictsWith: string[];
};

export type LegacySceneMigration = {
  legacyId: string;
  legacyLabel: string;
  archetypeId: AtmosphereSceneArchetypeId;
  variantId: string;
  migrationStatus: AtmosphereMigrationStatus;
  notes?: string;
};

export type ResolvedSceneVariantContent = {
  primaryTrace: string;
  supportingObjects: string[];
  spatialCue: string;
  timeOfDay?: string;
  compositionCue: string;
  wardrobeTrace?: string;
};

export type AtmosphereSceneResolution = {
  requestedSceneId?: string;
  resolvedArchetypeId: AtmosphereSceneArchetypeId;
  resolvedVariantId: string;
  usedFallback: boolean;
  fallbackReason?: AtmosphereFallbackReason;
};

const presence: ProductPresenceMode[] = ["no_product", "subtle_supporting_presence", "lifestyle_trace_presence"];

export const ATMOSPHERE_SCENE_ARCHETYPES: Record<AtmosphereSceneArchetypeId, AtmosphereSceneArchetype> = {
  ENTRYWAY_DEPARTURE: { id: "ENTRYWAY_DEPARTURE", label: "出门玄关", locationLock: "a private entryway immediately before departure", spatialType: "threshold", allowsWardrobeTrace: true, preferredProductPresenceModes: ["subtle_supporting_presence", "lifestyle_trace_presence"], requiredSpatialCues: ["entrance door and floor transition", "a compact key or bag landing point"], forbiddenSpatialCues: ["return-home aftermath", "market groceries", "bedroom"], compositionCue: "frame the door-floor relationship off center with shallow threshold depth", dominantPlane: "doorway", cameraHeight: "low", depthPattern: "corridor", dominantObject: "departure trace" },
  ENTRYWAY_ARRIVAL: { id: "ENTRYWAY_ARRIVAL", label: "回家玄关", locationLock: "a private entryway immediately after arrival", spatialType: "threshold", allowsWardrobeTrace: true, preferredProductPresenceModes: ["lifestyle_trace_presence", "subtle_supporting_presence"], requiredSpatialCues: ["recently closed entrance door", "weighted belongings just set down"], forbiddenSpatialCues: ["pre-departure preparation", "styled retail display", "bedroom"], compositionCue: "show the arrival path and grounded object weight from an off-center low view", dominantPlane: "floor", cameraHeight: "low", depthPattern: "corridor", dominantObject: "arrival trace" },
  WARDROBE_PREPARATION: { id: "WARDROBE_PREPARATION", label: "衣帽准备", locationLock: "a private wardrobe or dressing corner during preparation", spatialType: "indoor", allowsWardrobeTrace: true, preferredProductPresenceModes: ["subtle_supporting_presence", "lifestyle_trace_presence"], requiredSpatialCues: ["one garment rail, hook, chair, or mirror edge", "one recently handled clothing trace"], forbiddenSpatialCues: ["boutique display", "complete outfit flatlay", "commercial lookbook"], compositionCue: "use asymmetrical mirror-edge or rail-edge framing without a full outfit display", dominantPlane: "wall", cameraHeight: "slightly_high", depthPattern: "foreground_obstruction", dominantObject: "handled garment trace" },
  WINDOW_READING: { id: "WINDOW_READING", label: "窗边阅读", locationLock: "a quiet window-side reading or rest area", spatialType: "indoor", allowsWardrobeTrace: false, preferredProductPresenceModes: ["no_product", "subtle_supporting_presence"], requiredSpatialCues: ["window edge and side light", "reading material with a recent-use trace"], forbiddenSpatialCues: ["entry door", "office workstation", "decorative reading-room showroom"], compositionCue: "leave broad negative space beside the window from a calm seated-height view", dominantPlane: "window", cameraHeight: "eye_level", depthPattern: "layered", dominantObject: "reading trace" },
  WORKTABLE_PAUSE: { id: "WORKTABLE_PAUSE", label: "工作台暂停", locationLock: "a personal worktable during an interrupted task", spatialType: "indoor", allowsWardrobeTrace: false, preferredProductPresenceModes: ["no_product", "subtle_supporting_presence"], requiredSpatialCues: ["partial desk edge", "evidence of one interrupted task"], forbiddenSpatialCues: ["flatlay", "office-supply catalog", "product-development display"], compositionCue: "use an oblique tabletop view with one edge cropped and activity left unfinished", dominantPlane: "table", cameraHeight: "eye_level", depthPattern: "flat", dominantObject: "interrupted work trace" },
  RETURN_HOME_TABLE: { id: "RETURN_HOME_TABLE", label: "归家置物台", locationLock: "a sideboard or console shortly after returning home", spatialType: "indoor", allowsWardrobeTrace: false, preferredProductPresenceModes: ["lifestyle_trace_presence", "subtle_supporting_presence"], requiredSpatialCues: ["sideboard or console edge", "one weighted everyday item recently set down"], forbiddenSpatialCues: ["market produce spread", "entry door as hero", "styled flatlay"], compositionCue: "crop the console asymmetrically at lived-in standing height", dominantPlane: "table", cameraHeight: "slightly_high", depthPattern: "foreground_obstruction", dominantObject: "set-down item" },
  MARKET_RETURN_KITCHEN: { id: "MARKET_RETURN_KITCHEN", label: "采购归来", locationLock: "a kitchen counter or dining surface after a small local errand", spatialType: "indoor", allowsWardrobeTrace: false, preferredProductPresenceModes: ["lifestyle_trace_presence", "no_product"], requiredSpatialCues: ["counter or dining surface at lived-in height", "one unpacking trace with natural paper or bag weight"], forbiddenSpatialCues: ["styled food flatlay", "banquet", "grocery advertisement"], compositionCue: "group one primary purchase irregularly with only one or two supports", dominantPlane: "table", cameraHeight: "eye_level", depthPattern: "layered", dominantObject: "market return trace" },
  CAFE_FRONT: { id: "CAFE_FRONT", label: "咖啡馆外部", locationLock: "a real café frontage and adjoining pavement", spatialType: "outdoor", allowsWardrobeTrace: false, preferredProductPresenceModes: ["no_product", "subtle_supporting_presence"], requiredSpatialCues: ["façade-pavement relationship", "storefront glass or doorway depth"], forbiddenSpatialCues: ["residential interior", "blanket", "indoor reading room"], compositionCue: "use a wider street-side observation with façade and pavement both legible", dominantPlane: "wall", cameraHeight: "eye_level", depthPattern: "corridor", dominantObject: "storefront passage trace" },
  CAFE_INTERIOR: { id: "CAFE_INTERIOR", label: "咖啡馆室内", locationLock: "a quiet real café interior without check-in styling", spatialType: "indoor", allowsWardrobeTrace: false, preferredProductPresenceModes: ["no_product", "subtle_supporting_presence"], requiredSpatialCues: ["window-side or counter-side seating depth", "one recently used place"], forbiddenSpatialCues: ["café exterior", "food advertisement", "uniform amber commercial lighting"], compositionCue: "observe across a table or chair edge while preserving room depth", dominantPlane: "window", cameraHeight: "eye_level", depthPattern: "layered", dominantObject: "used café place" },
  BOOKSTORE_MAGAZINE: { id: "BOOKSTORE_MAGAZINE", label: "书店与文化空间", locationLock: "a bookstore, magazine shop, or quiet cultural retail space", spatialType: "indoor", allowsWardrobeTrace: false, preferredProductPresenceModes: ["no_product", "subtle_supporting_presence"], requiredSpatialCues: ["shelf or reading-table edge", "one browsing or purchase trace"], forbiddenSpatialCues: ["book product catalog", "souvenir shop", "empty CGI gallery"], compositionCue: "frame shelf rhythm and a pause point without making merchandise the hero", dominantPlane: "wall", cameraHeight: "eye_level", depthPattern: "corridor", dominantObject: "browsing trace" },
  HOTEL_STAY: { id: "HOTEL_STAY", label: "酒店短住", locationLock: "a recognizably temporary hotel stay", spatialType: "indoor", allowsWardrobeTrace: true, preferredProductPresenceModes: ["subtle_supporting_presence", "lifestyle_trace_presence"], requiredSpatialCues: ["temporary-room depth", "one restrained luggage, room-card, or itinerary trace"], forbiddenSpatialCues: ["ordinary residential bedroom", "hospitality advertisement", "centered bed hero"], compositionCue: "show temporary occupancy through room depth and one restrained travel trace", dominantPlane: "window", cameraHeight: "eye_level", depthPattern: "layered", dominantObject: "temporary stay trace" },
  RESIDENTIAL_TRANSITION: { id: "RESIDENTIAL_TRANSITION", label: "住宅公共过渡", locationLock: "a residential lobby, lift hall, or apartment corridor", spatialType: "threshold", allowsWardrobeTrace: false, preferredProductPresenceModes: ["no_product", "subtle_supporting_presence"], requiredSpatialCues: ["architectural wall-floor junction", "directional corridor, lift, or lobby depth"], forbiddenSpatialCues: ["private home entryway", "luxury hotel lobby", "commercial showroom"], compositionCue: "use architectural edges and directional waiting space with minimal objects", dominantPlane: "floor", cameraHeight: "eye_level", depthPattern: "corridor", dominantObject: "transit pause" },
  CITY_TRANSIT: { id: "CITY_TRANSIT", label: "城市移动", locationLock: "an ordinary urban movement path", spatialType: "outdoor", allowsWardrobeTrace: false, preferredProductPresenceModes: ["no_product", "subtle_supporting_presence"], requiredSpatialCues: ["real pavement and architectural edge", "a directional daily-movement trace"], forbiddenSpatialCues: ["tourism campaign", "landmark hero", "street-style portrait"], compositionCue: "use a wider directional frame with pavement, building scale, and movement path", dominantPlane: "floor", cameraHeight: "eye_level", depthPattern: "corridor", dominantObject: "movement trace" },
  MATERIAL_LIGHT_SPACE: { id: "MATERIAL_LIGHT_SPACE", label: "材质光影空间", locationLock: "a neutral material-and-light study with a faint daily trace", spatialType: "indoor", allowsWardrobeTrace: false, preferredProductPresenceModes: ["no_product"], requiredSpatialCues: ["one tactile surface", "visible natural-light transition"], forbiddenSpatialCues: ["specific competing room", "product display", "decorative flatlay"], compositionCue: "let light and material relation occupy generous asymmetric negative space", dominantPlane: "floor", cameraHeight: "low", depthPattern: "flat", dominantObject: "light transition" },
};

function variant(input: Omit<AtmosphereSceneVariant, "preferredProductPresenceModes" | "conflictsWith" | "wardrobeTracePool"> & Partial<Pick<AtmosphereSceneVariant, "preferredProductPresenceModes" | "conflictsWith" | "wardrobeTracePool">>): AtmosphereSceneVariant {
  return { preferredProductPresenceModes: presence, conflictsWith: [], wardrobeTracePool: [], ...input };
}

export const ATMOSPHERE_SCENE_VARIANTS: AtmosphereSceneVariant[] = [
  variant({ id:"commute_to_office", archetypeId:"CITY_TRANSIT", label:"通勤上班", description:"the walk from parking or transit toward work", compatibleSeasons:"all", primaryTracePool:["a work-bound route has just continued beyond frame","a brief pause before entering the office district"], supportingObjectPool:["folded transit receipt","compact work tote edge","unreadable access card"], spatialCuePool:["office-building edge beside real pavement","a restrained business-district corner"], timeOfDayPool:["early weekday morning","late-morning city light"], compositionCuePool:["follow the pavement direction toward the building","crop one architectural edge into the foreground"], allowsWardrobeTrace:false }),
  variant({ id:"weekend_city_walk", archetypeId:"CITY_TRANSIT", label:"周末城市散步", description:"a quiet weekend passage through a lived-in district", compatibleSeasons:"all", primaryTracePool:["a slow weekend walk has just passed","a short pause between neighborhood stops"], supportingObjectPool:["folded tote","bookstore receipt","small paper bag"], spatialCuePool:["tree shadow across worn pavement","a low-key neighborhood façade"], timeOfDayPool:["late weekend morning","soft afternoon"], compositionCuePool:["keep the walking path open through frame","observe across a curb or railing edge"], allowsWardrobeTrace:false }),
  variant({ id:"cafe_window_pass", archetypeId:"CAFE_FRONT", label:"咖啡店门口", description:"passing or pausing at a café window", compatibleSeasons:"all", primaryTracePool:["a takeaway stop has just ended","someone has paused briefly outside the window"], supportingObjectPool:["one takeaway cup","folded paper bag","small receipt"], spatialCuePool:["soft storefront reflection","restrained unreadable signage"], timeOfDayPool:["quiet morning","shaded afternoon"], compositionCuePool:["hold both pavement and glazing in frame","place the doorway off center"], allowsWardrobeTrace:false }),
  variant({ id:"cafe_window_seat_pause", archetypeId:"CAFE_INTERIOR", label:"咖啡馆内", description:"a brief pause at a real café window seat", compatibleSeasons:"all", primaryTracePool:["a chair remains slightly shifted after a short pause","one place shows recent quiet use"], supportingObjectPool:["used ceramic cup","folded napkin","unreadable magazine edge"], spatialCuePool:["window-side table with background counter depth","chair edge against soft glazing light"], timeOfDayPool:["mid-morning","late afternoon"], compositionCuePool:["look past a chair edge into room depth","crop the table rather than centering it"], allowsWardrobeTrace:false }),
  variant({ id:"quiet_friends_lunch", archetypeId:"CAFE_INTERIOR", label:"朋友午餐", description:"the quiet aftermath of a restrained friends lunch", compatibleSeasons:"all", primaryTracePool:["two places show a conversation has just paused","chairs remain naturally offset after lunch"], supportingObjectPool:["two simple glasses","folded menu edge","small shared plate cleared of food emphasis"], spatialCuePool:["daylit café table with circulation depth","a quiet corner away from the counter"], timeOfDayPool:["early lunch hour","soft midday"], compositionCuePool:["show two offset place settings without symmetry","use chair spacing to imply conversation"], allowsWardrobeTrace:false }),
  variant({ id:"gallery_browsing_pause", archetypeId:"BOOKSTORE_MAGAZINE", label:"美术馆", description:"a quiet browsing pause in a contemporary gallery", compatibleSeasons:"all", primaryTracePool:["a visitor route has moved beyond the frame","a bench-side pause has just ended"], supportingObjectPool:["folded exhibition leaflet","unreadable wall label edge","simple bench"], spatialCuePool:["correctly spaced artwork on soft-stone wall","controlled wall light and passage depth"], timeOfDayPool:["quiet daytime opening hours","late-afternoon gallery light"], compositionCuePool:["use wall rhythm and passage depth","keep artwork contextual rather than product-like"], allowsWardrobeTrace:false }),
  variant({ id:"magazine_shop_browsing", archetypeId:"BOOKSTORE_MAGAZINE", label:"书店 / 杂志店门口", description:"browsing at a bookstore or magazine shop threshold", compatibleSeasons:"all", primaryTracePool:["one publication has just been selected","a browsing pause continues beyond frame"], supportingObjectPool:["book edge","folded purchase receipt","plain paper carrier"], spatialCuePool:["shelf rhythm near the entrance","muted shopfront texture and reading ledge"], timeOfDayPool:["late morning","early evening"], compositionCuePool:["frame the threshold and shelf depth together","use a publication edge as a small foreground trace"], allowsWardrobeTrace:false }),
  variant({ id:"flower_market_return", archetypeId:"MARKET_RETURN_KITCHEN", label:"花店 / 买花", description:"returning with a modest paper-wrapped flower purchase", compatibleSeasons:["spring","summer","autumn"], primaryTracePool:["a small flower bundle has just been set down","wrapping paper is being loosened after returning"], supportingObjectPool:["plain flower paper","small receipt","folded canvas tote"], spatialCuePool:["kitchen counter edge","dining surface near an unpacking area"], timeOfDayPool:["late morning","soft afternoon"], compositionCuePool:["crop most stems and emphasize paper weight","keep the bundle off center with one support only"], allowsWardrobeTrace:false, conflictsWith:["romantic bouquet styling"] }),
  variant({ id:"premium_grocery_return", archetypeId:"MARKET_RETURN_KITCHEN", label:"精品超市 / 日常采购", description:"unpacking a small refined daily grocery errand", compatibleSeasons:"all", primaryTracePool:["one grocery bag is partly unpacked","a daily purchase has just reached the counter"], supportingObjectPool:["one seasonal produce item","small receipt","folded reusable tote"], spatialCuePool:["practical kitchen counter","dining surface beside storage"], timeOfDayPool:["late morning","early evening"], compositionCuePool:["show natural bag weight and one unpacked item","avoid overhead arrangement through a lived-in-height view"], allowsWardrobeTrace:false }),
  variant({ id:"neighborhood_market_return", archetypeId:"MARKET_RETURN_KITCHEN", label:"社区市集 / 精品买菜", description:"returning from a neighborhood produce market", compatibleSeasons:["spring","summer","autumn"], primaryTracePool:["a produce parcel has just been opened","a market tote rests with one item removed"], supportingObjectPool:["one seasonal vegetable","brown paper wrap","small handwritten-style receipt kept unreadable"], spatialCuePool:["kitchen work edge","informal dining-table corner"], timeOfDayPool:["weekend morning","late afternoon"], compositionCuePool:["use irregular grouping with visible paper folds","let the tote fall naturally beyond the table edge"], allowsWardrobeTrace:false }),
  variant({ id:"quiet_city_corner", archetypeId:"CITY_TRANSIT", label:"城市街角 / 安静街区", description:"a quiet contemporary city corner", compatibleSeasons:"all", primaryTracePool:["daily movement has just cleared the corner","a short street-side pause is implied"], supportingObjectPool:["folded local receipt","small paper carrier","subtle railing shadow"], spatialCuePool:["curb line and mildly worn pavement","building edge with restrained greenery"], timeOfDayPool:["mid-morning","late afternoon"], compositionCuePool:["turn the curb into a directional line","use a building edge as foreground obstruction"], allowsWardrobeTrace:false }),
  variant({ id:"rainy_city_transition", archetypeId:"CITY_TRANSIT", label:"雨天街角", description:"a calm city passage after light rain", compatibleSeasons:"all", primaryTracePool:["a rain pause has just ended","recent passage is visible through displaced water marks"], supportingObjectPool:["folded umbrella","small paper receipt protected from rain","subtle drain edge"], spatialCuePool:["slightly wet pavement","soft reflected daylight along a curb"], timeOfDayPool:["overcast morning","rain-clearing afternoon"], compositionCuePool:["follow reflections along the walking direction","keep wet pavement broad and objects small"], allowsWardrobeTrace:false }),
  variant({ id:"mixed_weekend_errand_return", archetypeId:"MARKET_RETURN_KITCHEN", label:"周末轻采购", description:"returning from one or two small weekend errands", compatibleSeasons:"all", primaryTracePool:["one small purchase is being unpacked","a folded tote rests after a short errand"], supportingObjectPool:["bakery paper","coffee-bean pouch","single produce item","small receipt"], spatialCuePool:["side counter near the kitchen","casual dining-table edge"], timeOfDayPool:["weekend noon","soft early evening"], compositionCuePool:["select one purchase as primary and one support","show a natural counter-height grouping"], allowsWardrobeTrace:false }),
  variant({ id:"hotel_arrival_luggage", archetypeId:"HOTEL_STAY", label:"旅行酒店", description:"arrival during a short hotel stay", compatibleSeasons:"all", primaryTracePool:["a compact case has just been opened","arrival items remain near the room threshold"], supportingObjectPool:["folded itinerary","room card","travel notebook"], spatialCuePool:["temporary-room curtain depth","chair and luggage relationship"], timeOfDayPool:["arrival afternoon","early evening"], compositionCuePool:["show luggage as a trace within room depth","keep the bed peripheral and unstyled"], allowsWardrobeTrace:true, wardrobeTracePool:["one folded travel layer at the chair edge"] }),
  variant({ id:"hotel_room_pause", archetypeId:"HOTEL_STAY", label:"酒店房间", description:"a brief pause inside a temporary hotel room", compatibleSeasons:"all", primaryTracePool:["a room-side routine has briefly paused","one travel item has been moved from the case"], supportingObjectPool:["room card","travel notebook","closed toiletry pouch"], spatialCuePool:["hotel curtain light and chair edge","recognizable temporary-room joinery"], timeOfDayPool:["quiet morning","late afternoon"], compositionCuePool:["use curtain-to-chair depth","crop the bed and avoid hospitality symmetry"], allowsWardrobeTrace:true, wardrobeTracePool:["one season-compatible travel garment folded on a chair edge"] }),
  variant({ id:"hotel_threshold_arrival", archetypeId:"RESIDENTIAL_TRANSITION", label:"酒店门口 / 门厅", description:"a restrained hotel threshold without promotional grandeur", compatibleSeasons:"all", primaryTracePool:["arrival direction continues through the threshold","a brief luggage pause is implied near the entrance"], supportingObjectPool:["small luggage wheel trace","folded itinerary","plain room-card sleeve"], spatialCuePool:["stone or wood threshold junction","door and lobby depth without a reception hero"], timeOfDayPool:["daytime arrival","early evening"], compositionCuePool:["frame threshold materials and directional depth","keep signage and hospitality cues secondary"], allowsWardrobeTrace:false }),
  variant({ id:"morning_wardrobe_preparation", archetypeId:"WARDROBE_PREPARATION", label:"居家衣帽间", description:"morning preparation in a private wardrobe", compatibleSeasons:"all", primaryTracePool:["one garment has just been handled","a final clothing choice remains unresolved"], supportingObjectPool:["single hanger","plain tote edge","mirror edge"], spatialCuePool:["private garment rail","chair beside wardrobe storage"], timeOfDayPool:["morning side light","late-morning preparation"], compositionCuePool:["use rail depth and mirror edge asymmetrically","crop most clothing to avoid display"], allowsWardrobeTrace:true, wardrobeTracePool:["one season-compatible outer or upper layer with natural folds"] }),
  variant({ id:"dressing_corner_final_check", archetypeId:"WARDROBE_PREPARATION", label:"衣帽间 / 更衣角", description:"a final check at a compact dressing corner", compatibleSeasons:"all", primaryTracePool:["a last adjustment has just ended","one selected item remains apart from storage"], supportingObjectPool:["single hanger","chair edge","small closed accessory pouch"], spatialCuePool:["mirror edge beside a hook","compact dressing chair and wall junction"], timeOfDayPool:["soft morning","early evening preparation"], compositionCuePool:["frame through a partial mirror without reflection of a person","keep one chosen trace off center"], allowsWardrobeTrace:true, wardrobeTracePool:["one selected season-compatible garment at the chair edge"] }),
  variant({ id:"weekday_entryway_departure", archetypeId:"ENTRYWAY_DEPARTURE", label:"玄关出门", description:"weekday departure from a private entryway", compatibleSeasons:"all", primaryTracePool:["keys have just been lifted from the landing point","a bag is positioned for immediate departure"], supportingObjectPool:["key tray","folded note","compact tote"], spatialCuePool:["door handle and floor transition","narrow entry console"], timeOfDayPool:["weekday morning","late-afternoon departure"], compositionCuePool:["show a clear route toward the door","keep the departure trace beside, not centered on, the threshold"], allowsWardrobeTrace:true, wardrobeTracePool:["one season-compatible light layer near the door"] }),
  variant({ id:"after_work_entryway_arrival", archetypeId:"ENTRYWAY_ARRIVAL", label:"回家进门", description:"arrival home after the day outside", compatibleSeasons:"all", primaryTracePool:["a weighted bag has just touched the floor","the entrance door appears newly closed"], supportingObjectPool:["small key tray","folded receipt","plain paper carrier"], spatialCuePool:["entry floor transition","hallway depth beyond the door"], timeOfDayPool:["early evening","late-afternoon return"], compositionCuePool:["emphasize floor contact and arrival direction","use the hallway as receding depth"], allowsWardrobeTrace:true, wardrobeTracePool:["one season-compatible layer loosely removed near the entry"] }),
  variant({ id:"afternoon_window_reading", archetypeId:"WINDOW_READING", label:"窗边阅读", description:"an afternoon reading pause beside a window", compatibleSeasons:"all", primaryTracePool:["a page has just been turned","reading has paused with the book left open"], supportingObjectPool:["open book","reading glasses","drinking glass"], spatialCuePool:["window edge and curtain line","chair or side-table edge"], timeOfDayPool:["soft afternoon","late-afternoon side light"], compositionCuePool:["leave generous space beyond the reading trace","use the window edge as a vertical frame"], allowsWardrobeTrace:false }),
  variant({ id:"private_window_magazine_pause", archetypeId:"WINDOW_READING", label:"窗边阅读角", description:"a private magazine pause at a compact window corner", compatibleSeasons:"all", primaryTracePool:["a magazine remains open at an uneven page","glasses have just been set beside the reading material"], supportingObjectPool:["magazine","glasses","plain water glass"], spatialCuePool:["small side table near a window","chair edge against a curtain"], timeOfDayPool:["late morning","quiet early evening"], compositionCuePool:["crop the chair and table into separate planes","avoid pairing a drink with decorative flowers"], allowsWardrobeTrace:false }),
  variant({ id:"work_notes_pause", archetypeId:"WORKTABLE_PAUSE", label:"工作台 / 桌边整理", description:"a pause while organizing daily work notes", compatibleSeasons:"all", primaryTracePool:["a note has been shifted mid-task","a pen rests after one unfinished line"], supportingObjectPool:["notebook","used pen","glasses","laptop edge"], spatialCuePool:["personal desk edge","paper overlap with natural contact"], timeOfDayPool:["working morning","late-afternoon pause"], compositionCuePool:["use an oblique crop across the desk edge","keep papers irregular and sparse"], allowsWardrobeTrace:false }),
  variant({ id:"material_sample_review", archetypeId:"WORKTABLE_PAUSE", label:"材质工作台", description:"a restrained review of small material samples", compatibleSeasons:"all", primaryTracePool:["two small samples have just been compared","one material note remains unfinished"], supportingObjectPool:["unlabeled material sample","care brush","plain color card","used pencil"], spatialCuePool:["tactile work surface","sample edge meeting paper notes"], timeOfDayPool:["neutral daytime","soft studio afternoon"], compositionCuePool:["show material contact at an oblique angle","avoid a catalog grid or complete product board"], allowsWardrobeTrace:false }),
  variant({ id:"shooting_table_pause", archetypeId:"WORKTABLE_PAUSE", label:"拍摄花絮", description:"a quiet pause between image-production tasks", compatibleSeasons:"all", primaryTracePool:["a shot list has just been checked","one styling adjustment has paused off frame"], supportingObjectPool:["shot-list edge","camera-monitor edge","plain tape roll","folded reflector edge"], spatialCuePool:["working studio table edge","partial light-stand base in depth"], timeOfDayPool:["daytime production","late-afternoon setup"], compositionCuePool:["let one technical edge prove context without dominating","crop the table as an interrupted workspace"], allowsWardrobeTrace:false }),
  variant({ id:"studio_launch_between_takes", archetypeId:"WORKTABLE_PAUSE", label:"棚内上新拍摄", description:"a restrained studio moment between launch takes", compatibleSeasons:"all", primaryTracePool:["the next setup is not yet complete","a quiet reset is underway beyond frame"], supportingObjectPool:["folded shot list","reflector edge","plain styling clip"], spatialCuePool:["warm-white seamless edge","light-stand base and working table relation"], timeOfDayPool:["controlled daytime session","late session"], compositionCuePool:["show working edges rather than a finished campaign set","keep equipment fragmentary and secondary"], allowsWardrobeTrace:false }),
  variant({ id:"summer_amusement_pause", archetypeId:"CITY_TRANSIT", label:"暑假游乐园", description:"a restrained summer amusement-park rest point", compatibleSeasons:["summer"], primaryTracePool:["a family outing has paused in shade","the route continues toward a distant ride area"], supportingObjectPool:["folded park map","plain paper wristband","canvas tote"], spatialCuePool:["shaded park walkway","distant defocused ride structure"], timeOfDayPool:["summer morning","shaded afternoon"], compositionCuePool:["keep ride evidence distant and the walkway dominant","avoid promotional landmark framing"], allowsWardrobeTrace:false }),
  variant({ id:"mediterranean_seaside_pause", archetypeId:"HOTEL_STAY", label:"海边度假", description:"a restrained Mediterranean seaside hotel threshold", compatibleSeasons:["summer"], primaryTracePool:["a coastal walk has paused near the hotel threshold","one travel item rests before returning outside"], supportingObjectPool:["sunglasses case","book edge","woven bag edge"], spatialCuePool:["pale limestone threshold","quiet sea-facing depth"], timeOfDayPool:["soft summer morning","late shaded afternoon"], compositionCuePool:["keep coast context architectural rather than postcard-like","frame limestone and open depth without resort advertising"], allowsWardrobeTrace:true, wardrobeTracePool:["one light summer travel layer"] }),
  variant({ id:"grassland_picnic_pause", archetypeId:"CITY_TRANSIT", label:"草原野餐", description:"a restrained open-field picnic pause", compatibleSeasons:["spring","summer","autumn"], primaryTracePool:["a small picnic has briefly paused","one reading item remains beside the field edge"], supportingObjectPool:["folded picnic textile edge","woven basket edge","paperback book","fruit box"], spatialCuePool:["open-field edge","clear grassland horizon"], timeOfDayPool:["mild late morning","soft afternoon"], compositionCuePool:["keep the field context wider than the objects","show only one compact picnic grouping"], allowsWardrobeTrace:false }),
  variant({ id:"hotel_holiday_routine", archetypeId:"HOTEL_STAY", label:"酒店度假", description:"a quiet holiday routine inside a hotel", compatibleSeasons:["spring","summer","autumn"], primaryTracePool:["a light travel routine has just paused","one day-trip item remains near the terrace threshold"], supportingObjectPool:["travel tote","closed sunglasses case","folded itinerary"], spatialCuePool:["terrace threshold with room depth","temporary chair-side storage"], timeOfDayPool:["holiday morning","late afternoon"], compositionCuePool:["connect terrace and room without resort grandeur","keep luggage and leisure cues peripheral"], allowsWardrobeTrace:true, wardrobeTracePool:["one light season-compatible travel garment"] }),
  variant({ id:"family_road_trip_pause", archetypeId:"CITY_TRANSIT", label:"亲子自驾出行", description:"a mature, uncluttered family road-trip pause", compatibleSeasons:"all", primaryTracePool:["a compact travel pouch has just been repositioned","the route continues after a short car-side pause"], supportingObjectPool:["folded paper map","small snack pouch","compact child travel case"], spatialCuePool:["passenger-side or car-side edge","ordinary roadside or parking texture"], timeOfDayPool:["travel morning","late-afternoon stop"], compositionCuePool:["keep vehicle evidence partial and non-advertising","follow the loading direction rather than centering objects"], allowsWardrobeTrace:false }),
  variant({ id:"summer_return_home", archetypeId:"ENTRYWAY_ARRIVAL", label:"暑假外出后回家", description:"returning home after a summer day out", compatibleSeasons:["summer"], primaryTracePool:["a light tote has just been set down","the entry still holds an airy return-home trace"], supportingObjectPool:["sun hat edge","folded note","light grocery bag"], spatialCuePool:["ventilated entry threshold","apartment hallway depth"], timeOfDayPool:["summer evening","late shaded afternoon"], compositionCuePool:["show light object weight at the floor transition","keep the doorway open in the composition"], allowsWardrobeTrace:true, wardrobeTracePool:["one thin summer layer loosely set aside"] }),
  variant({ id:"urban_park_walk", archetypeId:"CITY_TRANSIT", label:"公园慢走", description:"a relaxed path through an urban park", compatibleSeasons:"all", primaryTracePool:["a slow walk has moved beyond frame","a bench-side pause has just ended"], supportingObjectPool:["folded tote","paperback edge","small railing shadow"], spatialCuePool:["real walking path","bench or railing with restrained greenery"], timeOfDayPool:["quiet morning","late afternoon"], compositionCuePool:["use the path as a directional line","keep greenery contextual rather than decorative"], allowsWardrobeTrace:false }),
  variant({ id:"residential_neighborhood_path", archetypeId:"RESIDENTIAL_TRANSITION", label:"社区步道", description:"a practical neighborhood walking transition", compatibleSeasons:"all", primaryTracePool:["daily movement continues toward the residential buildings","a short wait has occurred near the path junction"], supportingObjectPool:["small parcel edge","folded local notice kept unreadable","subtle railing shadow"], spatialCuePool:["community paving and curb","residential building depth"], timeOfDayPool:["weekday morning","early evening"], compositionCuePool:["connect path direction to residential scale","use curb and façade as separate depth planes"], allowsWardrobeTrace:false }),
  variant({ id:"weekend_trip_departure", archetypeId:"ENTRYWAY_DEPARTURE", label:"周末轻旅行出发", description:"departing for a short weekend trip", compatibleSeasons:"all", primaryTracePool:["a compact case is positioned for departure","travel papers have just been checked near the door"], supportingObjectPool:["small travel tote","folded itinerary","plain paper bag"], spatialCuePool:["building threshold","entry floor transition beside compact luggage"], timeOfDayPool:["weekend morning","early-afternoon departure"], compositionCuePool:["show the outward route beyond the luggage","keep travel items compact and off center"], allowsWardrobeTrace:true, wardrobeTracePool:["one season-compatible travel layer near the case"] }),
  variant({ id:"keys_and_bag_sideboard", archetypeId:"RETURN_HOME_TABLE", label:"钥匙与包袋归家置物", description:"a brief sideboard pause after returning home", compatibleSeasons:"all", primaryTracePool:["keys and a weighted bag have just reached the sideboard","a daily carry item rests before being put away"], supportingObjectPool:["small key tray","folded receipt","glasses case","phone placed face down"], spatialCuePool:["sideboard edge near a hallway","console surface with residential depth"], timeOfDayPool:["early evening","late-afternoon return"], compositionCuePool:["crop the console at standing height","show item weight without an overhead layout"], allowsWardrobeTrace:false }),
  variant({ id:"parcel_and_receipt_sideboard", archetypeId:"RETURN_HOME_TABLE", label:"快递与票据归家置物", description:"a small parcel and receipt paused on a home console", compatibleSeasons:"all", primaryTracePool:["a compact parcel has just been set down","a receipt remains beside one unopened delivery"], supportingObjectPool:["small plain parcel","folded receipt","paper cutter kept closed","glasses case"], spatialCuePool:["hallway console edge","sideboard beside residential circulation"], timeOfDayPool:["weekday evening","quiet afternoon"], compositionCuePool:["use parcel weight and console depth as separate planes","keep packaging sparse and unreadable"], allowsWardrobeTrace:false }),
  variant({ id:"rainy_cafe_front", archetypeId:"CAFE_FRONT", label:"雨天咖啡馆外部", description:"a calm café frontage after light rain", compatibleSeasons:"all", primaryTracePool:["a short rain shelter pause has just ended","the pavement route resumes beyond the café door"], supportingObjectPool:["folded umbrella","one takeaway cup","small paper bag"], spatialCuePool:["wet pavement beneath storefront reflection","café doorway beside a rain-darkened curb"], timeOfDayPool:["rain-clearing morning","overcast afternoon"], compositionCuePool:["use reflection direction across the pavement","keep the façade wider than any object"], allowsWardrobeTrace:false }),
  variant({ id:"neutral_material_light_study", archetypeId:"MATERIAL_LIGHT_SPACE", label:"纯材质光影空间", description:"a neutral fallback or explicit material-light study", compatibleSeasons:"all", primaryTracePool:["natural light has shifted across one surface","one faint daily contact trace remains"], supportingObjectPool:["plain paper edge","matte ceramic fragment","frosted glass edge"], spatialCuePool:["tactile wall-floor junction","one quiet surface under changing light"], timeOfDayPool:["neutral daytime","late side light"], compositionCuePool:["leave most of the frame as calm negative space","separate light, shadow, and material planes asymmetrically"], allowsWardrobeTrace:false, preferredProductPresenceModes:["no_product"] })
  ,variant({ id:"textile_stone_light_relation", archetypeId:"MATERIAL_LIGHT_SPACE", label:"织物与石材光影关系", description:"a quiet relation between one textile edge, stone, and natural light", compatibleSeasons:"all", primaryTracePool:["a textile edge has shifted slightly across stone","light separates two restrained material planes"], supportingObjectPool:["plain textile edge","matte stone surface","unreadable paper fragment"], spatialCuePool:["stone floor meeting a quiet wall","window light crossing two material planes"], timeOfDayPool:["soft morning","late side light"], compositionCuePool:["keep material planes large and objects nearly absent","use asymmetric light falloff as the composition"], allowsWardrobeTrace:false, preferredProductPresenceModes:["no_product"] })
];

export const LEGACY_SCENE_MIGRATIONS: LegacySceneMigration[] = NON_PRODUCT_ATMOSPHERE_SCENES.map((legacyLabel) => {
  const resolved = ATMOSPHERE_SCENE_VARIANTS.find((item) => item.label === legacyLabel);
  if (!resolved) throw new Error(`ATMOSPHERE_LEGACY_SCENE_UNMAPPED:${legacyLabel}`);
  return { legacyId: legacyLabel, legacyLabel, archetypeId: resolved.archetypeId, variantId: resolved.id, migrationStatus: "normalized" };
});

export const ATMOSPHERE_VARIANT_BY_ID = Object.fromEntries(ATMOSPHERE_SCENE_VARIANTS.map((item) => [item.id, item])) as Record<string, AtmosphereSceneVariant>;
export const ATMOSPHERE_VARIANT_BY_LEGACY_LABEL = Object.fromEntries(ATMOSPHERE_SCENE_VARIANTS.map((item) => [item.label, item])) as Record<string, AtmosphereSceneVariant>;

export function isVariantSeasonCompatible(variant: AtmosphereSceneVariant, season: AtmosphereSeasonId): boolean {
  return variant.compatibleSeasons === "all" || variant.compatibleSeasons.includes(season);
}

function stableHash(value: string): number {
  let hash = 2166136261;
  for (let index = 0; index < value.length; index += 1) hash = Math.imul(hash ^ value.charCodeAt(index), 16777619);
  return hash >>> 0;
}

function selectOne(values: string[], seed: string, fallback: string): string {
  const candidates = values.filter(Boolean);
  return candidates.length ? candidates[stableHash(seed) % candidates.length] : fallback;
}

export function resolveSceneVariantContent(variant: AtmosphereSceneVariant, profile: SeasonSemanticProfile, seed: string): ResolvedSceneVariantContent {
  const compatibleObjects = variant.supportingObjectPool.filter((item) => !profile.conflictsWith.some((term) => item.toLowerCase().includes(term.toLowerCase())));
  const first = selectOne(compatibleObjects, `${seed}:object:1`, "one restrained everyday trace");
  const remaining = compatibleObjects.filter((item) => item !== first);
  const second = remaining.length && stableHash(`${seed}:object-count`) % 2 === 1 ? selectOne(remaining, `${seed}:object:2`, "") : "";
  return {
    primaryTrace: selectOne(variant.primaryTracePool, `${seed}:trace`, variant.description),
    supportingObjects: [first, second].filter(Boolean),
    spatialCue: selectOne(variant.spatialCuePool, `${seed}:space`, "one scene-specific spatial cue"),
    timeOfDay: selectOne(variant.timeOfDayPool, `${seed}:time`, ""),
    compositionCue: selectOne(variant.compositionCuePool, `${seed}:composition`, ATMOSPHERE_SCENE_ARCHETYPES[variant.archetypeId].compositionCue),
    wardrobeTrace: variant.allowsWardrobeTrace ? selectOne(variant.wardrobeTracePool, `${seed}:wardrobe`, "one local garment trace") : undefined,
  };
}

export function resolveAtmosphereScene(input: { requestedScene?: string; season: AtmosphereSeasonId; seed: string; excludedArchetypes?: AtmosphereSceneArchetypeId[] }): { archetype: AtmosphereSceneArchetype; variant: AtmosphereSceneVariant; resolution: AtmosphereSceneResolution } {
  const fallback = ATMOSPHERE_VARIANT_BY_ID.neutral_material_light_study;
  if (input.requestedScene && input.requestedScene !== "自动匹配") {
    const requested = ATMOSPHERE_VARIANT_BY_LEGACY_LABEL[input.requestedScene] ?? ATMOSPHERE_VARIANT_BY_ID[input.requestedScene];
    if (!requested) return { archetype: ATMOSPHERE_SCENE_ARCHETYPES.MATERIAL_LIGHT_SPACE, variant: fallback, resolution: { requestedSceneId: input.requestedScene, resolvedArchetypeId: "MATERIAL_LIGHT_SPACE", resolvedVariantId: fallback.id, usedFallback: true, fallbackReason: "unknown_legacy_scene" } };
    if (!isVariantSeasonCompatible(requested, input.season)) return { archetype: ATMOSPHERE_SCENE_ARCHETYPES.MATERIAL_LIGHT_SPACE, variant: fallback, resolution: { requestedSceneId: input.requestedScene, resolvedArchetypeId: "MATERIAL_LIGHT_SPACE", resolvedVariantId: fallback.id, usedFallback: true, fallbackReason: "season_incompatible_scene" } };
    return { archetype: ATMOSPHERE_SCENE_ARCHETYPES[requested.archetypeId], variant: requested, resolution: { requestedSceneId: input.requestedScene, resolvedArchetypeId: requested.archetypeId, resolvedVariantId: requested.id, usedFallback: false } };
  }
  const candidates = ATMOSPHERE_SCENE_VARIANTS.filter((item) => item.archetypeId !== "MATERIAL_LIGHT_SPACE" && isVariantSeasonCompatible(item, input.season) && !input.excludedArchetypes?.includes(item.archetypeId));
  if (!candidates.length) return { archetype: ATMOSPHERE_SCENE_ARCHETYPES.MATERIAL_LIGHT_SPACE, variant: fallback, resolution: { resolvedArchetypeId: "MATERIAL_LIGHT_SPACE", resolvedVariantId: fallback.id, usedFallback: true, fallbackReason: "no_compatible_variant" } };
  const selected = candidates[stableHash(`${input.seed}:variant`) % candidates.length];
  return { archetype: ATMOSPHERE_SCENE_ARCHETYPES[selected.archetypeId], variant: selected, resolution: { resolvedArchetypeId: selected.archetypeId, resolvedVariantId: selected.id, usedFallback: false } };
}
