import { readFile, writeFile, mkdir } from "node:fs/promises";
import { shoeCategoryRegistry } from "../src/modules/product/shoe/shoeCategoryRegistry";
import { createGarmentProductAdapter } from "../src/modules/product/garment/garmentProductAdapter";
import type { ShoeProductContext } from "../src/modules/product/shoe/shoeProductTypes";
import type { GarmentProductContext } from "../src/modules/product/garment/garmentProductTypes";
import type { ProductAdapterInput } from "../src/modules/product/types";
import { lifestyleSoftSeedingScenePool } from "../src/data/lifestyleSoftSeedingScenePool";

async function loadExistingConfig(path: string) {
  return JSON.parse(await readFile(path, "utf8"));
}

const existingGarmentImagePrompt = await loadExistingConfig("exports/product-config/theruiz-aura-garment-imagePrompt.v1.json");
const existingGarmentSeeding = await loadExistingConfig("exports/product-config/theruiz-aura-garment-seeding.v1.json");

const input: ProductAdapterInput = { imageType: "产品上脚图", extraRequirement: "", productPresent: true, scenePreference: "自动匹配", sceneKey: "default", season: "春", userSpecifiedStyling: false, generationNonce: 0, seriesImageCount: 1 };
const shoe = Object.fromEntries(Object.entries(shoeCategoryRegistry).map(([category, adapter]) => {
  const context: ShoeProductContext = { mode: "shoe", shoe: "Cloud Dancer 云舞者", customShoe: "", category: category as ShoeProductContext["category"] };
  const prompt = adapter.createPromptAdapter(context);
  return [category, { status: adapter.status, fieldSchema: adapter.getFieldSchema(), referenceRequirements: adapter.getReferenceRequirements(), shotPlan: adapter.getShotPlanProfile(), accuracyGuards: adapter.getAccuracyGuards(input), negativeRules: adapter.getNegativeRules(input), contentProfile: adapter.getContentProfile?.(), promptRules: { product: prompt.buildProductLine(input), accuracy: prompt.buildAccuracyLines(input), visibility: prompt.buildVisibilityLines(input), clipping: prompt.buildClippingLines(input), scene: prompt.buildSceneControlLines(input), imageType: prompt.buildImageTypeLines(input), actionSafety: prompt.buildActionSafetyLines(input), negative: prompt.buildNegativePhrases(input), stylingBoundary: prompt.buildStylingBoundaryLines(input), quality: prompt.getProductSpecificQualityLines(input) } }];
}));
const garmentContext: GarmentProductContext = { mode: "garment", garment: { category: "other", name: "selected garment", keyDetails: [] } };
const garment = createGarmentProductAdapter(garmentContext);
const garmentConfig = { mode: "garment", categories: ["dress", "top", "shirt", "knitwear", "tshirt", "trousers", "skirt", "coat", "jacket", "suit", "set", "activewear", "bridal", "eveningGown", "other"], specFields: ["category", "name", "silhouette", "neckline", "shoulderStructure", "sleeveType", "sleeveLength", "waistline", "hemLength", "garmentLength", "closure", "fabric", "color", "pattern", "drape", "transparency", "buttons", "pockets", "pleats", "darts", "panelBoundaries", "embroidery", "lace", "beadwork", "keyDetails"], referenceStylingPolicy: existingGarmentImagePrompt.referenceStylingPolicy, promptRules: { product: garment.buildProductLine(input), accuracy: garment.buildAccuracyLines(input), visibility: garment.buildVisibilityLines(input), clipping: garment.buildClippingLines(input), scene: garment.buildSceneControlLines(input), imageType: garment.buildImageTypeLines(input), actionSafety: garment.buildActionSafetyLines(input), negative: garment.buildNegativePhrases(input), stylingBoundary: existingGarmentImagePrompt.promptRules.stylingBoundary, quality: garment.getProductSpecificQualityLines(input) }, isolation: { forbiddenShoeOwnership: ["shoe identity", "toe box", "outsole", "laces", "sneaker silhouette", "heel geometry"] } };
const seedingBoundary = { owner: "category-seeding", notPromptCompiler: true, excludedOwners: ["other-product-identity", "provider-runtime"], noModelIds: true };
const shoeSeeding = { mode: "shoe", role: "seeding", boundary: { ...seedingBoundary, owner: "shoe-seeding", forbiddenGarmentOwnership: ["garment silhouette", "dress construction", "sleeve construction", "hemline as primary subject"] }, sourceFiles: ["src/modules/product/shoe/*Adapter.ts", "src/data/lifestyleSoftSeedingScenePool.ts"], categoryContentProfiles: Object.fromEntries(Object.entries(shoe).map(([category, value]) => [category, (value as any).contentProfile ?? null])), lifestyleScenes: lifestyleSoftSeedingScenePool.filter((scene) => /sneaker|shoe|foot|walk|ground|steps|commute|departure/i.test(`${scene.description} ${scene.extraRequirement}`)), sampling: { supportedCounts: [1, 3, 5, 8], preserveProductIdentity: true, keepTargetCategoryPrimary: true } };
const garmentSeeding = { mode: "garment", role: "seeding", boundary: { ...seedingBoundary, owner: "garment-seeding", forbiddenShoeOwnership: ["shoe identity", "toe box", "outsole", "laces", "heel geometry"] }, sourceFiles: ["src/modules/product/garment/garmentShotPlans.ts", "src/data/lifestyleSoftSeedingScenePool.ts", "src/data/activePromptTemplates.ts"], lifestyleScenes: lifestyleSoftSeedingScenePool.filter((scene) => !/sneaker|shoe identity|outsole|toe box/i.test(`${scene.description} ${scene.extraRequirement}`)).map(({ garmentTypePreference: _garmentTypePreference, ...scene }) => scene), outfitSeeds: {}, stylingAssembly: existingGarmentSeeding.stylingAssembly, supportingStyling: existingGarmentSeeding.supportingStyling, activePromptTemplates: existingGarmentSeeding.activePromptTemplates, sampling: { supportedCounts: [1, 3, 5, 8], preserveGarmentIdentity: true, keepGarmentCategoryPrimary: true } };
await mkdir("exports/product-config", { recursive: true });
await writeFile("exports/product-config/theruiz-aura-shoe-config.v1.json", JSON.stringify({ schemaVersion: "theruiz-aura-product-config.v1", mode: "shoe", source: "src/modules/product/shoe", categories: shoe }, null, 2) + "\n");
await writeFile("exports/product-config/theruiz-aura-garment-config.v1.json", JSON.stringify({ schemaVersion: "theruiz-aura-product-config.v1", mode: "garment", source: "src/modules/product/garment", ...garmentConfig }, null, 2) + "\n");
await writeFile("exports/product-config/theruiz-aura-shoe-imagePrompt.v1.json", JSON.stringify({ schemaVersion: "theruiz-aura-product-config.v1", mode: "shoe", role: "imagePrompt", source: "src/modules/product/shoe", categories: shoe, boundary: { owner: "shoe-imagePrompt", targetOnly: true, doesNotOwn: ["garment business rules", "provider runtime", "model id"] } }, null, 2) + "\n");
await writeFile("exports/product-config/theruiz-aura-shoe-seeding.v1.json", JSON.stringify({ schemaVersion: "theruiz-aura-product-config.v1", ...shoeSeeding }, null, 2) + "\n");
await writeFile("exports/product-config/theruiz-aura-garment-imagePrompt.v1.json", JSON.stringify({ schemaVersion: "theruiz-aura-product-config.v1", mode: "garment", role: "imagePrompt", source: "src/modules/product/garment", ...garmentConfig, boundary: { owner: "garment-imagePrompt", targetOnly: true, doesNotOwn: ["shoe business rules", "provider runtime", "model id"] } }, null, 2) + "\n");
await writeFile("exports/product-config/theruiz-aura-garment-seeding.v1.json", JSON.stringify({ schemaVersion: "theruiz-aura-product-config.v1", ...garmentSeeding }, null, 2) + "\n");
console.log("Exported shoe and garment configs without changing prompt runtime.");
