import { build } from "esbuild";
import { mkdir, mkdtemp, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join, resolve } from "node:path";
import { pathToFileURL } from "node:url";

const root = resolve(import.meta.dirname, "..");
const outDir = join(root, "docs", "prompt-audit", "phase-2");
await mkdir(outDir, { recursive: true });
const temp = await mkdtemp(join(tmpdir(), "theruiz-ab-"));
const entry = join(temp, "entry.ts");
const bundle = join(temp, "bundle.mjs");
await writeFile(entry, `export { compilePrompt } from ${JSON.stringify(resolve(root, "src/prompt-engine/compilePrompt.ts"))};\n`);
await build({ entryPoints: [entry], bundle: true, outfile: bundle, format: "esm", platform: "node", target: "node20", logLevel: "silent" });
const { compilePrompt } = await import(pathToFileURL(bundle));

const definitions = [
  { caseId: "P2-01-product-studio-hero", type: "product_studio", purpose: "hero_product studio launch", productRole: "hero_product", humanRole: "full_person", season: "春", action: "balanced studio stance", composition: "fullFigure", scenePreference: "棚内上新拍摄", hasShoe: true, selectedProduct: "confirmed uploaded sneaker reference" },
  { caseId: "P2-02-model-on-foot-studio", type: "model_on_foot", purpose: "shoe-to-foot physical integrity", productRole: "hero_product", humanRole: "partial_person", season: "夏", action: "one foot slightly forward", composition: "studioOnFootDetail", scenePreference: "棚内上新拍摄", hasShoe: true, selectedProduct: "confirmed uploaded sneaker reference" },
  { caseId: "P2-03-lifestyle-city-walking", type: "lifestyle_city", purpose: "walking action without shoe deformation", productRole: "visible_supporting_product", humanRole: "full_person", season: "春", action: "slow daily walk", composition: "onFootLifestyle", scenePreference: "通勤上班", hasShoe: true, selectedProduct: "confirmed uploaded sneaker reference" },
  { caseId: "P2-04-mirror-full-shoe", type: "mirror_selfie", purpose: "mirror geometry and full shoe visibility", productRole: "visible_supporting_product", humanRole: "no_face", season: "秋", action: "mirror outfit check", composition: "mirrorFull", scenePreference: "居家衣帽间", hasShoe: true, selectedProduct: "confirmed uploaded sneaker reference" },
  { caseId: "P2-05-craft-closeup", type: "craft_closeup", purpose: "confirmed heel/material detail without full-person leakage", productRole: "hero_product", humanRole: "no_full_person", season: "冬", action: "craft evidence close-up", composition: "materialDetail", scenePreference: "拍摄花絮", hasShoe: true, selectedProduct: "confirmed uploaded sneaker reference" },
  { caseId: "P2-06-subtle-atmosphere", type: "non_product_atmosphere", purpose: "peripheral product trace in wide atmosphere", productRole: "subtle_supporting_presence", humanRole: "no_person", season: "夏", action: "quiet daily trace", composition: "atmosphere", scenePreference: "城市街角 / 安静街区", hasShoe: false, selectedProduct: "none" },
  { caseId: "P2-07-no-product-no-person", type: "non_product_atmosphere", purpose: "no_product + no_person exclusion", productRole: "no_product", humanRole: "no_person", season: "冬", action: "still spatial moment", composition: "atmosphere", scenePreference: "工作台 / 桌边整理", hasShoe: false, selectedProduct: "none" },
  { caseId: "P2-08-summer-dark-product", type: "product_studio", purpose: "summer semantics with dark confirmed product", productRole: "hero_product", humanRole: "full_person", season: "夏", action: "restrained studio stance", composition: "fullFigure", scenePreference: "棚内上新拍摄", hasShoe: true, selectedProduct: "confirmed dark uploaded sneaker reference" },
];

function compile(definition) {
  return compilePrompt({
    brandId: "theruiz_aura", imageType: definition.hasShoe ? (definition.type === "product_studio" ? "产品上脚图" : definition.type === "model_on_foot" ? "产品上脚图" : definition.type === "lifestyle_city" ? "生活场景图" : definition.type === "mirror_selfie" ? "对镜穿搭图" : "拍摄花絮 / 材质图") : "非产品氛围图",
    compositionMode: definition.composition, scenePreference: definition.scenePreference, season: definition.season,
    modelChoice: definition.humanRole === "no_person" || definition.humanRole === "no_full_person" ? "不需要模特" : "30–45岁客户画像模特",
    modelContinuity: "新人物", hasShoe: definition.hasShoe, garmentTypePreference: "自动匹配", userExtraRequirement: "", isMultiImage: false,
    generationNonce: 17, provider: "image2", atmosphereProductPresenceMode: definition.productRole === "subtle_supporting_presence" ? "subtle_supporting_presence" : undefined,
    atmosphereProductPaletteEchoMode: definition.productRole === "subtle_supporting_presence" ? "material_translation" : undefined,
  });
}

const cases = definitions.map((definition) => {
  const a = compile(definition).prompt;
  const b = compile(definition).prompt;
  return { ...definition, referencePlan: definition.hasShoe ? { order: ["shoe-front", "shoe-side"], uploadRoles: ["primary product view", "secondary product view"] } : { order: [], uploadRoles: [] }, aPrompt: a, bPrompt: b, aChars: a.length, bChars: b.length, semanticDifference: "A = PRE-AUDIT commit adb7cba output; B = POST-AUDIT commit 162c027 output. Prompt text is expected to be identical where the rule-ID guard is not exercised.", expectedRisks: ["product truth", "physical integrity", "composition execution", "brand expression"], generationRecommendation: 2, humanReview: { status: "pending", conclusion: null, evidence: "", productTruthDeclined: null, brandDeclined: null, compositionImproved: null, actionImproved: null, suspectedAdjectiveCompetition: null, suspectedEmphasisWeakening: null, recommendOptimization: null, targetModule: null } };
});

const reviewForm = {
  scoring: { productTruth: ["shoe silhouette", "toe box", "outsole", "panels", "material", "color", "laces and tongue", "product proportion"], physicalIntegrity: ["foot-shoe relation", "garment separation", "grounding", "no floating", "no clipping", "no duplicated shoe", "body anatomy"], composition: ["product role", "subject relation", "shot scale", "negative space", "product readability", "commercial usability"], humanAction: ["action naturalness", "action stability", "human realism", "facial naturalness", "clothing-action relation", "product attention balance"], brand: ["Quiet Warm Luxury", "restraint", "warmth", "mature urban feeling", "material realism", "low-saturation order", "no generic AI polish"], artifacts: ["plastic CGI", "generic catalog", "over-styled", "artificial pose", "over-smoothed skin", "visual clutter", "fake material", "excessive symmetry", "prompt literalism", "product deformation"] },
  scale: "1-5; humanRole no_person/no_full_person items may be N/A and must be explicitly marked.",
  conclusions: ["B_CLEARLY_BETTER", "B_SLIGHTLY_BETTER", "EQUIVALENT", "A_SLIGHTLY_BETTER", "A_CLEARLY_BETTER", "BOTH_FAIL", "INVALID_TEST"],
};
await writeFile(join(outDir, "phase-2-ab-cases.json"), JSON.stringify({ phase: "PHASE_2_AB_PREPARATION_READY", aSource: "adb7cba5e75bbd08a2093f631e0caee7d779c5c1", bSource: "162c027", cases }, null, 2) + "\n");
await writeFile(join(outDir, "phase-2-visual-results.json"), JSON.stringify({ phase: "PHASE_2_AB_PREPARATION_READY", status: "NOT_READY", results: cases.map(({ caseId, humanRole }) => ({ caseId, humanRole, status: "pending", conclusion: null, scores: null, evidence: "", failureTypes: [], recommendOptimization: null, targetModule: null })) }, null, 2) + "\n");
await writeFile(join(outDir, "PHASE_2_AB_TEST_PLAN.md"), `# Phase 2 A/B Test Plan\n\nStatus: **PHASE_2_AB_PREPARATION_READY**\n\nA = PRE-AUDIT compile output from commit \`adb7cba5e75bbd08a2093f631e0caee7d779c5c1\`. B = POST-AUDIT compile output from commit \`162c027\`. The current Phase 1 rule-ID guard is expected to be output-neutral for these cases; this must be confirmed by the actual prompt text and then by Image2 visual review.\n\n- Cases: ${cases.length}\n- Recommended images: 2 per A/B version\n- Total recommended images: ${cases.length * 4}\n- Use identical product references, order, model source, season, and scene settings.\n- Do not infer results from text length. Review stability across both generations.\n\nThe complete prompts and per-case metadata are in \`phase-2-ab-cases.json\` and \`PHASE_2_AB_PROMPTS.md\`.\n`);
await writeFile(join(outDir, "PHASE_2_AB_PROMPTS.md"), `# Phase 2 A/B Prompts\n\nUse the same uploaded reference images in the same order for A and B. Generate two images per version. Do not change the product, model, season, scene, or reference order between versions.\n\n${cases.map((item) => `## ${item.caseId}\n\n- Test goal: ${item.purpose}\n- Product role: ${item.productRole}\n- Human role: ${item.humanRole}\n- Season: ${item.season}\n- Action: ${item.action}\n- Composition: ${item.composition}\n- Reference order: ${item.referencePlan.order.length ? item.referencePlan.order.join(" → ") : "none"}\n- Upload roles: ${item.referencePlan.uploadRoles.join("; ") || "no product references"}\n- Recommended generation count: ${item.generationRecommendation} per version\n\n### A Prompt — PRE-AUDIT (${item.aChars} chars)\n\n\`\`\`text\n${item.aPrompt}\n\`\`\`\n\n### B Prompt — POST-AUDIT (${item.bChars} chars)\n\n\`\`\`text\n${item.bPrompt}\n\`\`\`\n\nExecution note: compare product truth, physical integrity, composition, action, brand expression, and artifacts. Do not score a missing human category when the case has no person.\n`).join("\n")}`);
await writeFile(join(outDir, "PHASE_2_VISUAL_REVIEW_FORM.md"), `# Phase 2 Visual Review Form\n\nFor each generated image, score applicable items from 1 to 5. Mark N/A only for categories excluded by the case human/product role.\n\n## Required fields\n\n- Case ID and image ID\n- Version: A or B\n- Product Truth: silhouette, toe box, outsole, panels, material, color, laces/tongue, proportion\n- Physical Integrity: foot/shoe relation, garment separation, grounding, floating, clipping, duplicate shoe, anatomy\n- Composition: product role, subject relation, shot scale, negative space, readability, commercial usability\n- Human/Action when applicable: naturalness, stability, realism, face, clothing/action relation, product attention balance\n- Brand: Quiet Warm Luxury, restraint, warmth, mature urban feeling, material realism, low-saturation order, AI polish\n- Artifact tags: plastic CGI, generic catalog, over-styled, artificial pose, over-smoothed skin, clutter, fake material, excessive symmetry, prompt literalism, deformation\n\n## Case conclusion\n\nChoose exactly one: B_CLEARLY_BETTER, B_SLIGHTLY_BETTER, EQUIVALENT, A_SLIGHTLY_BETTER, A_CLEARLY_BETTER, BOTH_FAIL, INVALID_TEST. Record evidence, whether Product Truth declined, suspected adjective competition, suspected emphasis weakening, optimization recommendation, and target module.\n`);
await writeFile(join(outDir, "PHASE_2_TARGETED_OPTIMIZATION_REPORT.md"), `# Phase 2 Targeted Optimization Report\n\nStatus: **PHASE_2_AB_PREPARATION_READY**\n\nNo visual results have been supplied. No Prompt semantic optimization has been applied in Phase 2.\n\nThe next step is to execute the 8 cases in \`PHASE_2_AB_PROMPTS.md\`, generate 2 images for A and 2 for B per case, then fill \`phase-2-visual-results.json\`. Only complete, valid human evidence may authorize a targeted code change.\n`);
console.log(`Prepared ${cases.length} Phase 2 A/B cases (${cases.length * 4} recommended images).`);
