import { readFile, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join, resolve } from "node:path";
import { loadCommercialV13Api, stableStringify } from "./commercialV13Harness.mjs";

const projectRoot = resolve(import.meta.dirname, "..");
const api = await loadCommercialV13Api(projectRoot);
const assert = (condition, message) => {
  if (!condition) throw new Error(message);
};

const coverage = [
  "silhouette",
  "toe_structure",
  "side_panel_structure",
  "heel_structure",
  "outsole_profile",
  "color_blocking",
  "material_evidence",
];
const intents = [
  "URBAN_MOTION",
  "DAILY_STYLING",
  "QUIET_LUXURY",
  "PRODUCT_CRAFT",
  "NEW_ARRIVAL",
];
const concepts = Object.keys(api.COMMERCIAL_DIRECTOR_CONCEPT_CATALOG);
const autoNonces = [0, 1, 2, 3, 4];
const forcedNonces = [0, 1, 2];

function reference(mode, label) {
  if (mode === "confirmed") {
    return {
      referenceSetId: `authority-confirmed-${label}`,
      taskId: "commercial-authority-consolidation-phase-b",
      sourceType: "current_task_reference_set",
      confirmationStatus: "confirmed",
      confirmedReferenceCount: 2,
      confirmedAssetIds: ["front", "side"],
      coverage,
      missingCoverage: [],
      referencePlanReady: true,
      productTruthMode: "reference_bound",
      productTruth: {
        coverage,
        status: "draft",
        referenceEvidenceBound: true,
        productTruthMode: "reference_bound",
      },
    };
  }
  return {
    referenceSetId: `authority-zero-${label}`,
    taskId: "commercial-authority-consolidation-phase-b",
    sourceType: "current_task_reference_set",
    confirmationStatus: "incomplete",
    confirmedReferenceCount: 0,
    confirmedAssetIds: [],
    coverage: [],
    missingCoverage: coverage,
    referencePlanReady: false,
    productTruthMode: "reference_bound",
    productTruth: null,
  };
}

function request(input) {
  return {
    commercialIntent: input.intent,
    directorConceptOverride: input.concept,
    generationNonce: input.nonce,
    characterSelection: { ageProfileId: "age_33_37", appearanceGroupId: "asian" },
    season: "秋",
    lifestyleFeeling: "安静 / 自然 / 克制",
    duration: 15,
    reference: reference(input.mode, `${input.intent}-${input.concept ?? "auto"}-${input.nonce}-${input.mode}`),
  };
}

function diagnosticCodes(outcome) {
  return outcome.status === "GENERATED"
    ? outcome.plan.finalExecutionPlan.validation.diagnostics.map((entry) => entry.code)
    : outcome.diagnostics ?? [];
}

function priorityBlockCode(outcome) {
  if (outcome.status !== "BLOCKED") return null;
  if (outcome.code === "DIRECTOR_CONCEPT_RESOURCE_INCOMPATIBLE") return "BLOCKED_RESOURCE";
  if (outcome.code === "DIRECTOR_CONCEPT_CAMERA_INCOMPATIBLE") return "BLOCKED_CAMERA";
  if (outcome.code === "DIRECTOR_CONCEPT_EVENT_INCOMPATIBLE") return "BLOCKED_EVENT";
  const codes = diagnosticCodes(outcome);
  if (
    codes.some((entry) => /UNDECLARED_PHYSICAL_RESOURCE|DEVICE_RESOURCE_MISSING/.test(entry))
  ) return "BLOCKED_RESOURCE";
  if (
    codes.some((entry) => /DEVICE_CAMERA_INCOMPATIBLE/.test(entry))
  ) return "BLOCKED_CAMERA";
  if (
    codes.some((entry) => /REVEAL_CONFLICT|DEVICE_TAKE_INCOMPATIBLE|INVALID_TAKE_COVERAGE/.test(entry))
  ) return "BLOCKED_REVEAL";
  return "BLOCKED_OTHER";
}

const autoCases = [];
let autoGenerated = 0;
let autoValid = 0;
let autoRenderValid = 0;
let autoBlocked = 0;
const autoReasonCounts = {
  visibilityConflict: 0,
  undeclaredResources: 0,
  deviceCameraConflict: 0,
  revealConflict: 0,
  endingConflict: 0,
  takeConflict: 0,
};

for (const intent of intents) {
  for (const nonce of autoNonces) {
    for (const mode of ["zero", "confirmed"]) {
      const outcome = api.runCommercialV14Pipeline(request({ intent, nonce, mode, concept: undefined }));
      if (mode === "zero") {
        assert(outcome.status === "BLOCKED", `AUTO ${intent}/${nonce}/zero must be blocked without confirmed references.`);
        autoBlocked += 1;
        autoCases.push({ intent, nonce, mode, status: "EXPECTED_REFERENCE_BLOCK" });
        continue;
      }
      assert(outcome.status === "GENERATED", `AUTO ${intent}/${nonce}/${mode} blocked: ${outcome.reason}`);
      const finalPlan = outcome.plan.finalExecutionPlan;
      assert(finalPlan.status === "VALID", `AUTO ${intent}/${nonce}/${mode} Final Plan is ${finalPlan.status}.`);
      assert(
        outcome.plan.renderValidation.status === "VALID",
        `AUTO ${intent}/${nonce}/${mode} render validation failed: ${outcome.plan.renderValidation.diagnostics.join(" | ")}`
      );
      assert(
        stableStringify(outcome.plan.finalExecutionPlan) === stableStringify(
          api.runCommercialV14Pipeline(request({ intent, nonce, mode, concept: undefined })).plan.finalExecutionPlan
        ),
        `AUTO ${intent}/${nonce}/${mode} is not deterministic.`
      );
      autoGenerated += 1;
      autoValid += 1;
      autoRenderValid += 1;
      const codes = finalPlan.validation.diagnostics.map((entry) => entry.code);
      for (const code of codes) {
        if (code === "VISIBILITY_CONFLICT") autoReasonCounts.visibilityConflict += 1;
        if (code === "UNDECLARED_PHYSICAL_RESOURCE" || code === "DEVICE_RESOURCE_MISSING") autoReasonCounts.undeclaredResources += 1;
        if (code === "DEVICE_CAMERA_INCOMPATIBLE") autoReasonCounts.deviceCameraConflict += 1;
        if (code === "REVEAL_CONFLICT") autoReasonCounts.revealConflict += 1;
        if (code.startsWith("ENDING_")) autoReasonCounts.endingConflict += 1;
        if (code === "DEVICE_TAKE_INCOMPATIBLE" || code === "INVALID_TAKE_COVERAGE") autoReasonCounts.takeConflict += 1;
      }
      autoCases.push({
        intent,
        nonce,
        mode,
        effectiveConcept: outcome.plan.authorityConsolidation.effectiveDirectorConceptId,
        finalPlanStatus: finalPlan.status,
        validationCodes: codes,
      });
    }
  }
}

const forcedCases = [];
let forcedValid = 0;
let forcedRenderValid = 0;
let blockedResource = 0;
let blockedCamera = 0;
let blockedEvent = 0;
let blockedReveal = 0;
let blockedOther = 0;

for (const intent of intents) {
  for (const concept of concepts) {
    for (const nonce of forcedNonces) {
      const outcome = api.runCommercialV14Pipeline(request({ intent, nonce, mode: "confirmed", concept }));
      if (outcome.status === "GENERATED") {
        assert(
          outcome.plan.finalExecutionPlan.status === "VALID",
          `FORCED ${intent}/${concept}/${nonce} emitted GENERATED with BLOCKED Final Plan.`
        );
        assert(
          outcome.plan.renderValidation.status === "VALID",
          `FORCED ${intent}/${concept}/${nonce} render validation failed.`
        );
        forcedValid += 1;
        forcedRenderValid += 1;
        forcedCases.push({ intent, concept, nonce, status: "VALID_COMPATIBLE" });
      } else {
        const category = priorityBlockCode(outcome);
        if (category === "BLOCKED_RESOURCE") blockedResource += 1;
        else if (category === "BLOCKED_CAMERA") blockedCamera += 1;
        else if (category === "BLOCKED_REVEAL") blockedReveal += 1;
        else if (outcome.code === "DIRECTOR_CONCEPT_EVENT_INCOMPATIBLE") blockedEvent += 1;
        else blockedOther += 1;
        forcedCases.push({
          intent,
          concept,
          nonce,
          status: category ?? "BLOCKED_OTHER",
          code: outcome.code,
          reason: outcome.reason,
          diagnostics: outcome.diagnostics,
        });
      }
    }
  }
}

let legacyBefore = null;
try {
  const legacyPath = process.env.COMMERCIAL_ARCHITECTURE_MATRIX
    ?? join(tmpdir(), "commercial-film-full-architecture-matrix.json");
  const legacy = JSON.parse(await readFile(legacyPath, "utf8"));
  const generated = legacy.rows.filter((row) => row.baseStatus === "GENERATED" && row.v14Status === "GENERATED");
  legacyBefore = {
    visibility: generated.filter((row) => row.conflicts?.visibilityMismatchCount > 0).length,
    resources: generated.filter((row) => row.conflicts?.undeclaredCarrierCount > 0).length,
    cameraDevice: generated.filter((row) => row.conflicts?.cameraDeviceConflict || row.conflicts?.staticCameraConflict).length,
    reveal: generated.filter((row) => row.conflicts?.baseRevealMismatch).length,
    ending: generated.filter((row) => row.conflicts?.endingConflict).length,
    take: generated.filter((row) => row.conflicts?.cameraPlanVsEventSpine).length,
  };
} catch {
  legacyBefore = null;
}

const legacyAfter = {
  visibility: forcedCases.filter((entry) => (
    entry.code === "FINAL_EXECUTION_PLAN_BLOCKED"
    && (entry.diagnostics ?? []).some((diagnostic) => /VISIBILITY_CONFLICT/.test(diagnostic))
  )).length,
  resources: blockedResource,
  cameraDevice: blockedCamera,
  reveal: blockedReveal,
  ending: forcedCases.filter((entry) => (
    (entry.diagnostics ?? []).some((diagnostic) => /ENDING_/.test(diagnostic))
  )).length,
  take: forcedCases.filter((entry) => (
    (entry.diagnostics ?? []).some((diagnostic) => /TAKE|DEVICE_TAKE_INCOMPATIBLE|INVALID_TAKE_COVERAGE/.test(diagnostic))
  )).length,
  validCompatible: forcedValid,
};

const outputPath = process.env.COMMERCIAL_PHASE_B_OUTPUT
  ?? join(tmpdir(), "commercial-authority-consolidation-phase-b-matrix.json");
await writeFile(outputPath, `${JSON.stringify({
  generatedAt: new Date().toISOString(),
  auto: {
    cases: autoGenerated,
    valid: autoValid,
    renderValid: autoRenderValid,
    blocked: autoBlocked,
    reasonCounts: autoReasonCounts,
    cases: autoCases,
  },
  forced: {
    cases: forcedCases.length,
    validCompatible: forcedValid,
    renderValid: forcedRenderValid,
    blockedResource,
    blockedCamera,
    blockedEvent,
    blockedReveal,
    blockedOther,
    cases: forcedCases,
  },
  legacy124: {
    before: legacyBefore,
    after: legacyAfter,
  },
}, null, 2)}\n`);

console.log("COMMERCIAL AUTHORITY CONSOLIDATION PHASE B VALIDATION PASS:", JSON.stringify({
  auto: {
    cases: autoGenerated,
    valid: autoValid,
    renderValid: autoRenderValid,
    blocked: autoBlocked,
    reasonCounts: autoReasonCounts,
  },
  forced: {
    cases: forcedCases.length,
    validCompatible: forcedValid,
    renderValid: forcedRenderValid,
    blockedResource,
    blockedCamera,
    blockedEvent,
    blockedReveal,
    blockedOther,
  },
  legacy124: {
    before: legacyBefore,
    after: legacyAfter,
  },
  output: outputPath,
}, null, 2));
