import type { NarrativeTopicConfig, NarrativeTopicId } from "./types";
import type { SpatialAnchorId, SpatialEnvelope } from "../spatial/types";

export const NARRATIVE_TOPIC_CATALOG: NarrativeTopicConfig[] = [
  {
    id: "after_work_home",
    label: "下班回家",
    aliases: [],
    narrativeDefinition: "A continuous transition from public workday composure back into a private home state.",
    defaultCharacterStates: ["composed", "slightly socially depleted", "attention returning inward"],
    allowedMicroEventFamilies: ["key_delay", "bag_search", "small_threshold_adjustment"],
    preferredLocationWorlds: ["HOME_ARRIVAL"],
    forbiddenPatterns: ["work collapse", "phone argument", "dramatic exhaustion"],
    lifestyleTone: ["ordinary", "quiet", "observational"],
    defaultSceneLabels: ["电梯", "公寓走廊", "公寓门口", "玄关"],
    status: "ACTIVE",
  },
  {
    id: "weekend_alone",
    label: "周末独处",
    aliases: [],
    narrativeDefinition: "A short stretch of self-directed weekend time used at the character's own unhurried pace.",
    defaultCharacterStates: ["private", "unhurried", "comfortable"],
    allowedMicroEventFamilies: ["small_object_tidy", "window_pause", "decision_to_stay", "gentle_transition"],
    preferredLocationWorlds: ["WEEKEND_PRIVATE_TIME"],
    forbiddenPatterns: ["loneliness", "melancholy", "existential reflection", "dramatic solitude"],
    lifestyleTone: ["self-directed", "private", "comfortable"],
    defaultSceneLabels: ["窗边阅读", "衣帽间 / 更衣角"],
    status: "ACTIVE",
  },
  {
    id: "errand_outing",
    label: "出门办事",
    aliases: ["出门"],
    narrativeDefinition: "A departure for one ordinary, concrete but minor daily task.",
    defaultCharacterStates: ["prepared", "task-oriented", "not rushed"],
    allowedMicroEventFamilies: ["temperature_adjustment", "item_check", "threshold_pause"],
    preferredLocationWorlds: ["LEAVING_HOME"],
    forbiddenPatterns: ["fashion walk", "travel", "business event", "dramatic delay"],
    lifestyleTone: ["practical", "ordinary", "quiet"],
    defaultSceneLabels: ["玄关", "公寓门口", "住宅楼外"],
    status: "ACTIVE",
  },
  {
    id: "waiting_for_friend",
    label: "等朋友",
    aliases: ["等人"],
    narrativeDefinition: "Arriving slightly early and experiencing a short natural wait before a friend appears.",
    defaultCharacterStates: ["early", "observant", "unhurried"],
    allowedMicroEventFamilies: ["early_arrival", "staying_outside", "small_bag_adjustment"],
    preferredLocationWorlds: ["OFFICE_ENTRANCE_WAIT"],
    forbiddenPatterns: ["phone anxiety", "impatience", "late-arrival drama", "urging call"],
    lifestyleTone: ["calm", "observational", "understated"],
    defaultSceneLabels: ["写字楼门口"],
    status: "ACTIVE",
  },
  {
    id: "afternoon_cafe",
    label: "午后咖啡",
    aliases: ["咖啡馆", "买咖啡"],
    narrativeDefinition: "A brief afternoon pause inside a cafe that interrupts the otherwise continuous day.",
    defaultCharacterStates: ["moving", "slightly searching", "settling"],
    allowedMicroEventFamilies: ["counter_pause", "pocket_check", "small_table_settle"],
    preferredLocationWorlds: ["CAFE_VISIT"],
    forbiddenPatterns: ["cafe review", "coffee posing", "influencer check-in", "brand showcase"],
    lifestyleTone: ["quiet", "ordinary", "tactile"],
    defaultSceneLabels: ["咖啡馆内"],
    status: "ACTIVE",
  },
  {
    id: "bookstore_browse",
    label: "逛书店",
    aliases: ["周末书店"],
    narrativeDefinition: "Entering or passing through a bookstore without a purchase goal and noticing one small visual detail.",
    defaultCharacterStates: ["focused", "lightly distracted", "quietly interested"],
    allowedMicroEventFamilies: ["window_notice", "slow_down", "interior_browse_pause"],
    preferredLocationWorlds: ["BOOKSTORE_VISIT"],
    forbiddenPatterns: ["literary persona", "forced reading", "exaggerated surprise", "staged book pose"],
    lifestyleTone: ["quiet", "observational", "cultured"],
    defaultSceneLabels: ["书店 / 杂志店门口", "书店 / 杂志店内"],
    status: "ACTIVE",
  },
  {
    id: "returning_with_purchases",
    label: "采购归来",
    aliases: [],
    narrativeDefinition: "Returning from ordinary errands with items and re-entering the private home space.",
    defaultCharacterStates: ["moving", "burdened lightly", "adjusting"],
    allowedMicroEventFamilies: ["bag_handle_slip", "grip_adjustment", "entry_console_transition"],
    preferredLocationWorlds: ["RETURNING_WITH_PURCHASES"],
    forbiddenPatterns: ["shopping haul", "luxury shopping", "brand display", "large haul"],
    lifestyleTone: ["ordinary", "practical", "grounded"],
    defaultSceneLabels: ["公寓走廊", "归家玄关"],
    status: "ACTIVE",
  },
  {
    id: "after_school_pickup",
    label: "接孩子后",
    aliases: [],
    narrativeDefinition: "A short homeward transition after an ordinary school pickup, centered on the adult woman's lived experience.",
    defaultCharacterStates: ["moving", "attentive", "settling into the route"],
    allowedMicroEventFamilies: ["crossing_pause", "item_adjustment", "short_wait_for_passage"],
    preferredLocationWorlds: ["SCHOOL_PICKUP_TRANSITION"],
    forbiddenPatterns: ["child distress", "parent conflict", "school problem", "punishment", "child as hero model"],
    lifestyleTone: ["ordinary", "warm", "unhurried"],
    defaultSceneLabels: ["社区步道", "城市街角 / 安静街区"],
    status: "ACTIVE",
  },
  {
    id: "weekend_walk",
    label: "周末散步",
    aliases: [],
    narrativeDefinition: "A light, destination-free walk through a neighborhood, residential street, or quiet pedestrian route.",
    defaultCharacterStates: ["relaxed", "observant", "unhurried"],
    allowedMicroEventFamilies: ["pace_change", "path_shift", "short_passage_pause"],
    preferredLocationWorlds: ["NEIGHBORHOOD_WALK"],
    forbiddenPatterns: ["landscape film", "mountain travel", "grassland film", "slow-motion performance", "fashion walk"],
    lifestyleTone: ["quiet", "neighborhood", "ordinary"],
    defaultSceneLabels: ["公园慢走", "社区步道"],
    status: "ACTIVE",
  },
  {
    id: "after_lunch",
    label: "午餐之后",
    aliases: [],
    narrativeDefinition: "A small empty interval after lunch, spent outside the restaurant before the next task begins.",
    defaultCharacterStates: ["settled", "slightly unfocused", "not yet moving to the next task"],
    allowedMicroEventFamilies: ["direction_check", "window_notice", "short_walk_decision"],
    preferredLocationWorlds: ["AFTER_LUNCH_STREET"],
    forbiddenPatterns: ["food display", "restaurant advertisement", "social drama", "meal photography"],
    lifestyleTone: ["quiet", "transitional", "ordinary"],
    defaultSceneLabels: ["城市街角 / 安静街区", "周末城市散步"],
    status: "ACTIVE",
  },
  {
    id: "city_wandering",
    label: "城市闲逛",
    aliases: [],
    narrativeDefinition: "Moving and observing through city blocks without a task or destination.",
    defaultCharacterStates: ["open", "observant", "lightly moving"],
    allowedMicroEventFamilies: ["storefront_notice", "corner_direction_change", "street_detail_pause"],
    preferredLocationWorlds: ["URBAN_WANDERING"],
    forbiddenPatterns: ["city postcard", "tourist landmark", "check-in spot", "runway street photo"],
    lifestyleTone: ["urban", "observational", "low-key"],
    defaultSceneLabels: ["城市街角 / 安静街区", "商务区转角", "周末城市散步"],
    status: "ACTIVE",
  },
  {
    id: "evening_return_home",
    label: "傍晚回家",
    aliases: [],
    narrativeDefinition: "Returning home in the evening from ordinary outside life without implying the end of a workday.",
    defaultCharacterStates: ["steady", "familiar with the route", "not rushed"],
    allowedMicroEventFamilies: ["small_item_transfer", "entry_threshold_pause", "bag_settle"],
    preferredLocationWorlds: ["EVENING_HOME_RETURN"],
    forbiddenPatterns: ["office", "work bag", "work fatigue", "overtime"],
    lifestyleTone: ["evening", "quiet", "private"],
    defaultSceneLabels: ["住宅楼外", "回家进门"],
    status: "ACTIVE",
  },
  {
    id: "short_local_trip",
    label: "短途出行",
    aliases: [],
    narrativeDefinition: "A short local move from one ordinary city location to another without complex preparation.",
    defaultCharacterStates: ["prepared", "route-aware", "ordinary"],
    allowedMicroEventFamilies: ["item_check", "pickup_pause", "short_route_adjustment"],
    preferredLocationWorlds: ["SHORT_LOCAL_TRIP"],
    forbiddenPatterns: ["airport", "train station", "flight", "hotel", "suitcase", "vacation", "tourist", "long-distance travel"],
    lifestyleTone: ["practical", "urban", "unhurried"],
    defaultSceneLabels: ["社区步道", "写字楼门口"],
    status: "ACTIVE",
  },
];

// V1.1: every Topic declares the local goal of its 15-second slice, and the
// spatial family its Moments must stay inside. Both are narrative truth, not
// downstream inference.
export const TOPIC_LOCAL_GOALS: Record<NarrativeTopicId, string> = {
  after_work_home: "enter the home and let the public part of the day fall away",
  weekend_alone: "finish the small object adjustment and settle back into quiet time at home",
  errand_outing: "complete the small departure adjustment and continue outside in a settled state",
  waiting_for_friend: "hold the waiting position until the brief pause resolves",
  afternoon_cafe: "complete the pocket and card interaction and settle into the cafe flow",
  bookstore_browse: "enter the bookstore after noticing the window display",
  returning_with_purchases: "enter the home with the carried bag secured",
  after_school_pickup: "settle the carried items after the wait and continue the walk in a settled state",
  weekend_walk: "resolve the small adjustment and continue the walk in an easy rhythm",
  after_lunch: "settle the garment adjustment and resume an unhurried walk",
  city_wandering: "resolve the small notice and continue the walk",
  evening_return_home: "enter the home after the evening route",
  short_local_trip: "arrive at the nearby destination",
};

export const SPATIAL_ANCHOR_FAMILIES: Record<string, SpatialAnchorId[]> = {
  HOME_RETURN_FINAL_STRETCH: ["RESIDENTIAL_EXIT", "ELEVATOR_EXIT", "APARTMENT_HALLWAY", "APARTMENT_THRESHOLD", "ENTRYWAY", "HOME_INTERIOR"],
  PRIVATE_TIME: ["CLOAKROOM", "TABLE", "WINDOW_SIDE", "HOME_INTERIOR"],
  LEAVING_HOME: ["ENTRYWAY", "APARTMENT_THRESHOLD", "RESIDENTIAL_EXIT", "STREET", "COMMUNITY_PATH"],
  OFFICE_WAIT: ["STREET", "OFFICE_ENTRANCE", "COMMUNITY_PATH"],
  CAFE_VISIT: ["STREET", "CAFE_INTERIOR", "CAFE_COUNTER"],
  BOOKSTORE_VISIT: ["STREET", "SHOP_WINDOW", "SHOP_FRONT", "SHOP_INTERIOR"],
  COMMUNITY_WALK: ["STREET", "COMMUNITY_PATH", "RESIDENTIAL_EXIT", "OFFICE_ENTRANCE"],
  STREET_INTERVAL: ["STREET", "COMMUNITY_PATH", "SHOP_FRONT", "CAFE_INTERIOR"],
  ARRIVAL_SLICE: ["STREET", "COMMUNITY_PATH", "DESTINATION_APPROACH", "DESTINATION_ANCHOR", "OFFICE_ENTRANCE"],
};

export const TOPIC_SPATIAL_FAMILY: Record<NarrativeTopicId, keyof typeof SPATIAL_ANCHOR_FAMILIES> = {
  after_work_home: "HOME_RETURN_FINAL_STRETCH",
  weekend_alone: "PRIVATE_TIME",
  errand_outing: "LEAVING_HOME",
  waiting_for_friend: "OFFICE_WAIT",
  afternoon_cafe: "CAFE_VISIT",
  bookstore_browse: "BOOKSTORE_VISIT",
  returning_with_purchases: "HOME_RETURN_FINAL_STRETCH",
  after_school_pickup: "COMMUNITY_WALK",
  weekend_walk: "COMMUNITY_WALK",
  after_lunch: "STREET_INTERVAL",
  city_wandering: "STREET_INTERVAL",
  evening_return_home: "HOME_RETURN_FINAL_STRETCH",
  short_local_trip: "ARRIVAL_SLICE",
};

export function buildSpatialEnvelope(topicId: NarrativeTopicId): SpatialEnvelope {
  const family = TOPIC_SPATIAL_FAMILY[topicId];
  return {
    macroLocation: family,
    allowedAnchors: [...SPATIAL_ANCHOR_FAMILIES[family]],
    continuityMode: "CONTIGUOUS_ROUTE",
  };
}

export const NARRATIVE_TOPIC_IDS: NarrativeTopicId[] = NARRATIVE_TOPIC_CATALOG.map((topic) => topic.id);
